### ISSUE TITLE
Physical description: script/hand description

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#111]
@wsalesky We want to add a few items to "Physical description: script/hand description". This requires us to add child elements to the xpath attribute for the collaspibles in question. These changes have the result that only the first collapsible is displayed in manuForma (without elements however) and the latter two not at all. Could you take a look? 

This is what the config for this part looks like:

```
<elementGroups>
                <group groupLabel="Summary of script." groupNo="1">
                    <element xpath="tei:handDesc/tei:summary"/>
                </group>
                <group groupLabel="Script definition." groupNo="2"  repeatable="yes">
                    <element xpath="tei:scriptDesc/tei:scriptNote"/>
                </group>
                <group groupLabel="Scribal hand(s)." groupNo="3"  repeatable="yes">
                    <element xpath="tei:handDesc/tei:handNote"/>
                </group>
</elementGroups> 
```

**Comment by wsalesky** [comment]
@mMoliere This should be addressed with this pull request: https://github.com/majlis-erc/manuForma/pull/112

I did not another issue while testing this, and I will make a new bug for it.

**Comment by wsalesky** [comment]
@mMoliere can you clarify, what is not working? Maybe with screen shots. Also, what record are you using to test this on? Does it have the tei:scriptDesc/tei:scriptNote elements in the record already? If not can you try adding them and see if that solves the problem. I did notice when I tested the record that if the tei:scriptDesc/tei:scriptNote does not exist already there is no way to add it. I am working on that feature/bug tomorrow.

**Comment by mMoliere** [comment]
@wsalesky The files I work with have` tei:scriptDesc/tei:scriptNote`. They are 1.xml to 6.xml E.g. https://github.com/majlis-erc/majlis-data/blob/5a6f7e553eb7c670847b0fee21179485684c39ef/data/manuscripts/tei/1.xml#L206

This is what it looks like when opened in Firefox:

![Image](https://user-images.githubusercontent.com/73166992/233458347-7c22ae28-77d3-4d9a-8230-fd1b5376a5b9.png)

**Comment by mMoliere** [comment]
It works now. Thank you!
