### ISSUE TITLE
Preview in collapsible

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#117]
@wsalesky for some of the repeatable collapsibles we would like to display a preview of the contents in place of the `groupLabel`. This way we won't have to open each collapsible to find and work on certain data. It would be convenient, if we could select the fields to be displayed in the `config.xml`.

Here is a sketch: 

![Image](https://user-images.githubusercontent.com/73166992/233593383-462ceceb-34bf-4444-b7c1-93384f2aa408.jpg)

In this instance, we would also need the possibility to insert phrases like "fols." before `<locus>` and ":" before `<title>`. The elements would be separated by a space.

**Comment by wsalesky** [comment]
I will see what I can do.

**Comment by wsalesky** [comment]
@mMoliere What section is the above? Link to where it is in the config file?

**Comment by mMoliere** [comment]
@wsalesky This is the beginning of `msItem` in the Content description section https://github.com/majlis-erc/manuForma/blob/1e9464485e044447a796d8c5ecb8c2134f599bf3/forms/formGenerator/config.xml#L186

**Comment by wsalesky** [comment]
@mMoliere This should be fixed with version 1.09. Reopen if you find any issues with it.

**Comment by wsalesky** [comment]
Example of how to enable this is here in the config.xml line 214, the Content description section: 
<group groupLabel="Detailed description of text unit(s): title, author, language, rubrics, etc." groupLabelConditionalElement="./*:title" groupLabelXPath="concat('fols. ', ./*:locus, ' : ', ./*:title)" groupNo="2" repeatable="yes">
                    <element xpath="tei:msItem"/>
                </group>

The important additions are the groupLabelConditionalElement, which is the element that must have content to trigger the display (if empty it will display the default label 'Detailed description of text unit(s): title, author, language, rubrics, etc.'). The other attribute is groupLabelXPath which tells the xslt how to construct the label. In this case it is a combination of text and elements. I can help construct these XPaths if needed. The XSLT copies the xpath directly, so it is important to get it correct, or it can cause the form to throw an error.
