### ISSUE TITLE
XML-Fragments

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#13]
For our team to work productively, it would be a big advantage to facilitate the way elements can be added to the forms.

The way you add elements now is that you explicitly choose the element's name in the parent element. And you only get this element. If you work with data whose structure repeats itself this can become tiresome – In particular I am thinking of `msItem` and `provenance` in the manuscript forms. It would be a huge help if you had the ability to add an element PLUS all of its child elements and attributes. Is this feasible?

**Comment by wsalesky** [comment]
@mMoliere You want this as the default behavior? To always add all available child elements?

**Comment by mMoliere** [comment]
@wsalesky Yes, that would be helpful.

**Comment by wsalesky** [comment]
@mMoliere Okay, I will investigate.

**Comment by mMoliere** [comment]
@wsalesky Thank you!

**Comment by wsalesky** [comment]
This feature has been added. You will need to regenerate any forms you would like to use this feature with.

**Comment by wsalesky** [comment]
@mMoliere please test and close if it meets your expectations.

**Comment by mMoliere** [comment]
@wsalesky Thank you, I'll test it.

**Comment by mMoliere** [comment]
@wsalesky It is not working. I tested the `msItem` and `provenance` elements both on Firefox and on Chrome.

**Comment by mMoliere** [comment]
I tried the relations form. Unfortunately it does not work.

**Comment by mMoliere** [comment]
Almost. The elements are generated. Can you do it for the attributes as well?

**Comment by wsalesky** [comment]
Done. Upload new forms to view.
