### ISSUE TITLE
References

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#130]

**Comment by mMoliere** [comment]
@wsalesky There are two issues connected to the Zotero links:

1. When I use the lookup feature I can't find any title. I suppose to that database was lost when I had to set up the apps again on our server. I was not able to find information in our past communication how I can establish this connection.

2. The `bibl` element displays a text field for which the schema can't account for. It is supposed to just contain three child elements (`ptr`, `title` and `citedRange`). This ghostly field displays the content of these fields. How can we make it go away?

This problem exists both in the manuscript and in the person forms.

Here is an example: 

![Image](https://user-images.githubusercontent.com/73166992/235130920-d9f0f372-08b1-4abc-91ed-09fd26e13933.jpg)

And here is the schema for `bibl`:
https://github.com/majlis-erc/manuForma/blob/451208a17fa32fe9674ed84b879387b530a8aba0/forms/schemas/mss-accMat.xml#L122

**Comment by wsalesky** [comment]
@mMoliere Can you send me a step by step of where the problems are? Maybe even with screen shots?

**Comment by mMoliere** [comment]
@wsalesky 

1. Bibliography section in the MS module. All three elements (title, ptr and citedRange) are present.



![Image](https://user-images.githubusercontent.com/73166992/236427968-e06a2ea7-349c-49cb-8e3d-3e68d0debe82.png)

2. I open the look up feature.



![Image](https://user-images.githubusercontent.com/73166992/236428094-32b88727-372f-415d-97b3-b32ca8226ddb.png)

3. I search for an author and select a title.



![Image](https://user-images.githubusercontent.com/73166992/236428243-06ecad28-fec7-443d-b079-2a115ba2fc5a.png)

4. The link to the Zotero record is added to the ptr element – but the title and citedRange elements vanish.



![Image](https://user-images.githubusercontent.com/73166992/236428619-6b9f459b-3ae4-4e88-b03a-dc97e802bba0.png)

**Comment by wsalesky** [comment]
@wsalesky Note to self, this works as expected locally. Will have to update forms and see if that resolves the issue. May be a services, not xforms issue.

**Comment by wsalesky** [comment]
@mMoliere Since this works locally but not on the server, I wonder if you need to update the scripts in the in the services directory? /db/apps/manuForma/services   In particular make sure submit.xql and getControlledVocab.xql are updated. Let me know if that solves the problem.

**Comment by mMoliere** [comment]
@wsalesky I have updated all the scripts and cleared my cache. Still, it does not work as intended.

**Comment by mMoliere** [comment]
@wsalesky I have to reopen this issue: 

1. I have observed that the `citedRange` element is deleted when a record is linked. We need this element to cite accurately.
2. The team has asked that we load `//bibl[@subtype="bibliography"]` into the `title` element.

**Comment by wsalesky** [comment]
@mMoliere If you add the citedRange after the record is linked it does not get deleted. Because when you look up the bibliographic record the whole tei:bibl element is copied and inserted into the TEI record. It would be more code intensive to add each child element of the tei:bibl to the edited record. 

Can you clarify what you mean by point #2? a tei example of current vrs desired behavior would be great!

**Comment by mMoliere** [comment]
@wsalesky Understood, we can manually add the citedRange if that's easier.

Before the Zotero records are linked to manuForma, they are exported as TEI files. – Currently only the title elements of these files are loaded into the records. – Inside these files, there are also two pre-formatted citations as they could appear in a bibliography. If we load the one I have referenced above, our users get all the relevant information (author, title, year) to check the entry without the fuss of having extra fields.

**Comment by wsalesky** [comment]
Or another option could be: 

```
<bibl xmlns="http://www.tei-c.org/ns/1.0">
                    <bibl>
                        <title level="a">Exegesis' Methods of the Bible in the Dictionary of the Karaite David Ben Abraham Alfāsī, "Kitāb Jāmi' al-Alfāż" / דרכי הפרשנות למקרא במילונו של הקראי דוד בן אברהם אלפאסי, "כתאב ג'אמע אלאלפאט'"</title>
                        <title level="j">Beit Mikra: Journal for the Study of the Bible and Its World / בית מקרא: כתב-עת לחקר המקרא ועולמו</title>
                        <author>
                            <forename>Esther Gamliel</forename>
                            <surname>Barak</surname>
                        </author>
                        <ptr target="https://majlis.net/bibl/FM6G5JZV"/>
                    </bibl>
                    <bibl type="formatted" subtype="citation" resp="https://www.zotero.org/styles/chicago-note-bibliography-17th-edition">Esther Gamliel Barak, <title level="a">Exegesis’ Methods of the Bible in the Dictionary of the Karaite David Ben Abraham Alfāsī, ‘Kitāb Jāmi’ al-Alfāż’ / דרכי הפרשנות למקרא במילונו של הקראי דוד בן אברהם אלפאסי, ‘כתאב ג’אמע אלאלפאט’,’</title> <title level="m">Beit Mikra: Journal for the Study of the Bible and Its World / בית מקרא: כתב-עת לחקר המקרא ועולמו</title> נט, no. ב (2014): 76–128, http://www.jstor.org/stable/24305003.</bibl>
                </bibl>
```

**Comment by mMoliere** [comment]
@wsalesky Yes, pretty much:

```
<bibl xml:id="bibl-111">
                                <title>Esther Gamliel Barak, Exegesis’ Methods of the Bible in the Dictionary of the Karaite David Ben Abraham Alfāsī, ‘Kitāb Jāmi’ al-Alfāż’ / דרכי הפרשנות למקרא במילונו של הקראי דוד בן אברהם אלפאסי, ‘כתאב ג’אמע אלאלפאט’,’ Beit Mikra: Journal for the Study of the Bible and Its World / בית מקרא: כתב-עת לחקר המקרא ועולמו נט, no. ב (2014): 76–128, http://www.jstor.org/stable/24305003.</title>                                
                                <ptr target="https://majlis.net/bibl/ANVNIYZA"/>
                                <citedRange unit="pages">150</citedRange>
                            </bibl>
```

The complete entry should include `citedRange` (which we add by hand). And maybe it's possible to strip the two `title`-elements inside the entry?

**Comment by wsalesky** [comment]
@mMoliere Updated. Please test and close.

**Comment by wsalesky** [comment]
@mMoliere This 'ghost field' is not showing up on my local version, can you make sure your schemas are all up to date? (let me know if everything is up to date and you are still seeing it, I will do some troubleshooting.) The other issue should be resolved in the srophe application. See the pull request above.
