### ISSUE TITLE
Automatic IDs

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#14]
In records, we create a lot of attributes for identfiers (especially persons, places and relations). They combine the numerical filename with the occurrence of the identifier in the indvidual file. e.g. 451-4: filename 451.xml – numbered element 4.

This is the sort of thing that humans tend to forget or overlook. It would improve the quality of our records if these attributes could be filled in automatically.

**Comment by wsalesky** [comment]
@mMoliere I can do this as a post processing step, do you want me to automatically add the xml:id attributes to certain elements, or just update the values in existing xml:id attributes so they are correct? If the first, I will need a list of elements that will need an automatically generated xml:id attribute.

**Comment by mMoliere** [comment]
@wsalesky I want the first. I shall prepare the list of elements for you in the coming days.

**Comment by wsalesky** [comment]
@mMoliere sounds good.

**Comment by mMoliere** [comment]
# Relations
- ab/@xml:id="factoid-{ID}"
- ab/<idno type="URI">{Filenumber}-{ID}</idno>
- /ab/bibl/ptr/@target="{Filenumber}" [for first bibl BUT for following entries {look-up IDs for other records}]

# Place
! - …/listPlace/place/@xml:id="place-{Filenumber}"
- …/listPlace/place/placeName/@xml:id="name-{ID}"
- …/listPlace/place/bibl/@xml:id="bibl-{ID}"

# Work
- /text/body/bibl/@xml:id="work-{Filenumber}"
- /text/body/bibl/title/@xml:id="title-{ID}"
- /text/body/bibl/note/bibl/@xml:id="note-{ID}"
- /text/body/bibl/bibl/@xml:id="bibl-{ID}"

# Person
- /body/listPerson/person/@xml:id="person-{Filenumber}"
- /body/listPerson/person/persName/@xml:id="name-{ID}"
- /body/listPerson/person/bibl/@xml:id="bibl-{ID}"

# Manuscript

- ! …/msDesc@xml:id="ms-{Filenumber}"
- …/msDesc/msContents/msItem/@xml:id="item-{ID}"
- …/msDesc/physDesc/objectDesc/layoutDesc/layout/@xml:id="layout-{ID}"
- …/msDesc/physDesc/handDesc/handNote/@xml:id="hand-{ID}"
- …/msDesc/physDesc/additions/list/item/@xml:id="add-{ID}"
- …/msDesc/additional/listBibl/bibl/@xml:id="bibl-{ID}"

**Comment by wsalesky** [comment]
@mMoliere What element is the generated id attached to here? The ab element already has a generated id, see rules above, is this supposed to go a child element? 
`ab/{Filenumber}-{ID}`

**Comment by wsalesky** [comment]
@mMoliere Checking on on this, once I have some clarity I can get this done pretty quickly.

**Comment by mMoliere** [comment]
Sorry for the delay, I have been ill. 

1. `ab/{Filenumber}-{ID}` should be `ab/idno/{Filenumber}-{ID}`
2. Yes. Filenumber is the XML filenumber and the ID is the part that will be automatically generated.

**Comment by wsalesky** [comment]
@mMoliere I think this can be closed. Reopen if I'm wrong.
