### ISSUE TITLE
Strange compiling error

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#140]
@wsalesky When I want to compile the manuscript config, I receive the following error message: "Invalid attribute name:". This refers to line 2213 in the generateXForms.xsl

The strange thing is that the error is limited to the manuscript config, when I compile the persons config it goes through without an error. So there seems to be something wrong in the manuscript config. I have tried to work it out, but I failed. Since line 2213 is concerned with `@ident`, I have look through all instances of this attribut in the manuscript config, but nothing seems amiss. And I have ruled out any connection to the new collapsible preview. Can you take a look?

**Comment by wsalesky** [comment]
@mMoliere The bug appears to be here: https://github.com/majlis-erc/manuForma/blob/main/forms/schemas/mss-history.xml#L344

The attRef element does not allow for an ident attribute, if you change those to attDef it runs as expected.
