### ISSUE TITLE
Srophé

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#141]
@wsalesky I installed the newest version of the MAJLIS Srophé app on the server. Clearly this was a mistake …

When I try to open the app it now says:

```
<exception>
<path>/db/apps/majlis-data/modules/view.xql</path>
<message>
err:XPST0003 The ':=' notation is no longer accepted in map expressions: use ':' instead. [at line 23, column 33]
</message>
</exception>
```

I am puzzled because this error does not seem to be connected to the Srophé app, but the DATA app.

(Also I can't create issues in the Srophé repository. But that does not really bug me.)

**Comment by wsalesky** [comment]
@mMoliere I can access the app on the server. Are you looking at the /db/apps/majlis or /db/apps/majlis-data  the second will give you an error, but you do not need to access the data app, you access all the data via the majlis app.

Also, I have added issues to the srophe app, so you should now be able to add issues there.

**Comment by mMoliere** [comment]
@wsalesky Thank you. Now it works for me too. Maybe yesterday I wasn't focused anymore and I opened the wrong app. 

Thank you for enabling issues!
