### ISSUE TITLE
Admin metadata + Login

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#145]

**Comment by mMoliere** [comment]
@wsalesky In the "Admin metadata" menu, we want users to document their changes. Since we anticipate that people will work with hundreds of records, it would great to make this chore easier for them. 

I would like that the user name that we enter in the login be filled into the identifier field in the "Admin metadata" menu, when a user creates a new change entry. In addition, the date will be filled into the date field.

This way the users only need to write a sentence or two what they did to the record.


The image below illustrates which fields should be filled in for the users.

![Image](https://github.com/majlis-erc/manuForma/assets/73166992/714dcc4b-c96f-4046-9134-4058ffe2dbf4)

**Comment by wsalesky** [comment]
Added.
