### ISSUE TITLE
Error when submitting to GitHub

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#157]

**Comment by mMoliere** [comment]
@wsalesky When I want to submit a record to Github, I receive the following error:



![Image](https://github.com/majlis-erc/manuForma/assets/73166992/75005399-b66e-4f77-ace9-a87ed5c8c7f3)

I don't really know what to make of it. I checked the webhook, which works fine.

**Comment by wsalesky** [comment]
@mMoliere I will take a look
