### ISSUE TITLE
Bug: Bibliography look up returns no records

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#166]
@wsalesky When trying to search for entries the search in the look up window in the bibl element returns no results.
![Screenshot 2023-07-06 at 12 22 30](https://github.com/majlis-erc/manuForma/assets/73166992/4da78de8-289a-4fac-8bee-59890aa77c10)

The look up window in the title element displays a broken search bar.
![Screenshot 2023-07-06 at 12 36 52](https://github.com/majlis-erc/manuForma/assets/73166992/7e53d579-0742-4652-b2ab-cc4e3107d090)

**Comment by wsalesky** [comment]
Fixed. There was a missing, maybe a hiccup in the webhooks.
