### ISSUE TITLE
Interface Change: Display Name

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#17]
We want manuForma to display the name of the record at the top of the page.

→ titleSmt/title[level="a"]

**Comment by wsalesky** [comment]
Would you like me to replace this text with the title? 

<img width="1689" alt="Screen Shot 2022-11-08 at 1 37 54 PM" src="https://user-images.githubusercontent.com/1168206/200648486-f8a864cf-1677-405d-a9d2-92d8580b5bad.png">

**Comment by mMoliere** [comment]
Yes, that would be great

**Comment by wsalesky** [comment]
Fixed. This means the title is blank until a title is added.
