### ISSUE TITLE
New Feature: Lookup manuscript records

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#175]
@wsalesky At this location (/TEI/text/body/listBibl/msDesc/physDesc/ab/listBibl/bibl) we want another lookup – this time we want to look for other manuscript records.

The <title @level='a'> of the referenced record should be copied into the `<idno>` of the active record. And the the URI of the referenced record should be copied into the <ptr>.

This is what the result should look like:
```
<bibl>
<idno>Ms. London, BL, Or. 9165</idno>
<ptr target="https://jalit.org/manuscript/2/tei"/>
</bibl>
```

**Comment by wsalesky** [comment]
@mMoliere What would make the most sense to you for configuring different lookup elements? Currently we have all lookups defined at the top of the config.xml file: https://github.com/majlis-erc/manuForma/blob/main/forms/formGenerator/config.xml#L45

We can list them here, with an added xpath attribute, to be able to more accurately select which elements you want a lookup to appear on, OR we can move the lookup definition to the subform element. I think either will work fine, so let me know what you would prefer as the user.

**Comment by wsalesky** [comment]
@mMoliere Waiting for you on this one.

**Comment by mMoliere** [comment]
@wsalesky On the one hand I think this should be finely grained according to the requirements of the subform. E.g. in Codicological definition the `bibl` element should point to other manuscript records, while in Bibliography it points to Zotero records. But adding the lookup definition to every subform element would bloat the config even more. 

So, I would prefer the first solution: adding an XPath attribute to select which elements lookup which records in which subform.

**Comment by wsalesky** [comment]
@mMoliere just to clarify, you want the title to be copied into the idno? not a title? 

```
<bibl>
<idno>Ms. London, BL, Or. 9165</idno>
<ptr target="https://jalit.org/manuscript/2/tei"/>
</bibl>
```

**Comment by wsalesky** [comment]
@mMoliere  Also, is this the same thing: https://github.com/majlis-erc/manuForma/issues/268

**Comment by mMoliere** [comment]
@wsalesky Yes, the idno element. Unless this unnecessarily complicates things.

**Comment by wsalesky** [comment]
@mMoliere but what field do you want to search within the ms records? The whole record? the title? something else? All the other lookups operate on a specific element.

**Comment by mMoliere** [comment]
@wsalesky Sorry, I wasn't specific enough.

1. We want to search in `/TEI/teiHeader/fileDesc/titleStmt/title/@level="a"` 
2. The content of that field is copied into the `idno`.
3. And the URL is copied into `ptr/@target`.
