### ISSUE TITLE
Error in Codicological definition subform

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#179]
@wsalesky There is an error in Codicological definition subform that prompts multiple messages.

![Error03](https://github.com/majlis-erc/manuForma/assets/73166992/cc4883ba-b25c-4563-8044-4597f6e35f3c)
![Error02](https://github.com/majlis-erc/manuForma/assets/73166992/3c982e8a-f083-45ec-9a7e-3ce9112a7f2b)

**Comment by mMoliere** [comment]
@wsalesky the warning at the beginning of the page is still being displayed.

**Comment by wsalesky** [comment]
@mMoliere the files on the main branch do not look like they have been updated? This one: 
https://github.com/majlis-erc/manuForma/blob/main/forms/msSimple/ab.xhtml

Was updated 3 days ago. That may be causing the issue.

**Comment by mMoliere** [comment]
@wsalesky You are right, I did not realize that I had to run the stylesheet again.

Nevertheless, now that I have run the stylesheet and cleared my cache, the error is persisting.

**Comment by wsalesky** [comment]
@mMoliere Sorry about that, please try the newest version of the XSLT.

**Comment by wsalesky** [comment]
@mMoliere interesting. I will do some more troubleshooting.

**Comment by wsalesky** [comment]
@mMoliere I will investigate. Sorry about that.

**Comment by mMoliere** [comment]
Yes the patch helped. Thank you! Shall we keep this issue open until it is finalised?

**Comment by wsalesky** [comment]
@mMoliere Yes, lets leave it open. I will need to find a fix.
