### ISSUE TITLE
Record Preview

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#20]
I believe we discussed the preview option. Is there any progress?

**Comment by wsalesky** [comment]
Not yet

**Comment by wsalesky** [comment]
Finally have this working. Will be in the next release 1.9

**Comment by mMoliere** [comment]
@wsalesky That's great news!

**Comment by wsalesky** [comment]
@mMoliere this is be available with the latest version of the xslt v 1.09
