### ISSUE TITLE
Bibliography subform has reverted to earlier version?

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#211]
@wsalesky It seems that the Bibliography subform has reverted to an earlier version.

The lookup for that subform is supposed to copy the bible @type="formatted" element of the Zotero record  into the title element of the local bibl element. Instead, we get <title level="a">. The reference to the Zotero record is also in the wrong place.

Please pull reestablish the changes you had done just a few weeks ago.

This is an example:
![Screenshot 2023-07-13 at 10-30-38 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/12e4c3c2-7bcd-4ff7-b2b4-b7afa69820ee)

**Comment by mMoliere** [comment]
@wsalesky It seems that the updates you made in v. 1.19 were overwritten when I merged the changes of v. 1.20.

**Comment by wsalesky** [comment]
@mMoliere can you clarify what changed? It looks like it is working to me?

**Comment by mMoliere** [comment]
@wsalesky You are right, the changes came through. Weird.

We are almost there: The title of the Zotero record is copied twice: 1) into the title element (where we want it) and 2) into the bibl element (that's not where we want it).
![Screenshot 2023-07-14 at 15-18-45 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/6b83ca48-5096-49fe-b177-d7db57a9f21b)

**Comment by wsalesky** [comment]
@mMoliere please test version 1.21 for a fix for this.

**Comment by mMoliere** [comment]
@wsalesky that worked!

**Comment by mMoliere** [comment]
@wsalesky We are at the same place as last week.
![Screenshot 2023-07-17 at 22 22 56](https://github.com/majlis-erc/manuForma/assets/73166992/f9cf1cde-81c0-48bf-aadc-2de0517a0723)

**Comment by mMoliere** [comment]
@wsalesky Yes, you are right about xml:id. I will modify the template accordingly.

But the main issue is that the wrong `title` element from the Zotero record is copied. And that the URI should be copied into `ptr`. (see above)

**Comment by wsalesky** [comment]
@mMoliere can you do a hard refresh on that form? It seems to be working correctly for me? Unless I am missing something.
<img width="1306" alt="Screenshot 2023-07-17 at 5 25 25 PM" src="https://github.com/majlis-erc/manuForma/assets/1168206/6b733e8b-b9b0-473f-b94d-77d1a585cedf">

**Comment by mMoliere** [comment]
@wsalesky Yes, indeed. Thank you! (Was it just a matter of refreshing?)

**Comment by wsalesky** [comment]
@mMoliere I think so, the update is causing some odd side effects. But hopefully we will catch all the bugs!

**Comment by mMoliere** [comment]
@wsalesky This bug is back … 

![Screenshot 2023-07-26 at 16 20 27](https://github.com/majlis-erc/manuForma/assets/73166992/d847577a-cbbf-4fb1-82e5-505a0518e050)

**Comment by wsalesky** [comment]
@mMoliere did you just merge my changes from this morning? (just trying to isolate where it came back)

**Comment by mMoliere** [comment]
@wsalesky I merged some changes just now and yesterday. But not this morning.

**Comment by wsalesky** [comment]
@mMoliere okay, thanks, I will do some troubleshooting.

**Comment by wsalesky** [comment]
@mMoliere When I look at the forms on the server (using Chrome) I get the expected results: 
<img width="1710" alt="Screenshot 2023-07-30 at 9 44 36 AM" src="https://github.com/majlis-erc/manuForma/assets/1168206/c1633a60-11a2-4c44-9d60-67069c48611f">


I expect you are experiencing some caching issues with Firefox. Can you test in Chrome and confirm it is working there?

**Comment by mMoliere** [comment]
@wsalesky That's fascinating. When I test it in Chrome (I have wiped the cache) I also get the erroneous output.
![Screenshot 2023-07-31 at 10 18 32](https://github.com/majlis-erc/manuForma/assets/73166992/587c37e8-72bb-4b88-9441-13f0630a1c28)

**Comment by wsalesky** [comment]
@mMoliere I think we can close this? It is a result of the config.xml being overwritten.
