### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#22]
To me this is not a big priority – Everyone who matters can pull the records from GitHub.
Unless you can make this button run without too much work, I would tend to delete it.

**Comment by wsalesky** [comment]
@mMoliere This button does work, at least for me in Chrome. If it is not working for you can you tell me what browser you are using?

**Comment by mMoliere** [comment]
@wsalesky Yes, on Chrome it works for me. Usually, I work with Firefox. Please add the notice "(Chrome Only)" to the button until it is running on both browsers.

**Comment by wsalesky** [comment]
Changed the text, will investigate why it is not working in Firefox. 

Leave issue open.

**Comment by wsalesky** [comment]
@mMoliere I am going through and cleaning up the remaining issues. I have suppressed this button for the time being. 
https://github.com/majlis-erc/manuForma/pull/454
