### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#232]
@wsalesky The links on the start page are broken. You can't open the forms for manuscripts or other entries. 
Plus the logos in the footer are missing.
![Screenshot 2023-07-17 at 22 31 31](https://github.com/majlis-erc/manuForma/assets/73166992/6c227362-fe08-46a9-9be6-e87ffc8cbc7b)

**Comment by wsalesky** [comment]
Not all the files loaded. I will take a look.

**Comment by wsalesky** [comment]
@mMoliere should be working a little better now. Let me know.
