### ISSUE TITLE
Side menu illegible

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#233]
@wsalesky The side menu is illegible. The new design has a green background (the same as the header) against which the white labels are legible.

![Screenshot 2023-07-17 at 22 21 24](https://github.com/majlis-erc/manuForma/assets/73166992/efd0b610-e4fb-433b-b61a-8a11b5a8d068)

**Comment by wsalesky** [comment]
@mMoliere should be better now
