### ISSUE TITLE
Button labels don't line up

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#236]
@wsalesky The labels (sometimes) don't line up with the buttons in which they are contained. This seems to be case whenever the label text is preced by a special charcter like "✕" or "+".
![Screenshot 2023-07-17 at 22 25 53](https://github.com/majlis-erc/manuForma/assets/73166992/3288e172-8c5c-4e4c-b0f8-3932582ec0bb)

**Comment by wsalesky** [comment]
@mMoliere what section is the above screen shot from? I want to test my fix.

**Comment by mMoliere** [comment]
@wsalesky that would be content description.

**Comment by mMoliere** [comment]
@wsalesky The buttons are now even more out of alignment with the text:
![Screenshot 2023-07-18 at 22 26 18](https://github.com/majlis-erc/manuForma/assets/73166992/6f55c932-e7fd-471b-b5da-e68c94b7a7ca)

**Comment by wsalesky** [comment]
What browser? On Jul 18, 2023, at 4:28 PM, mMoliere ***@***.***> wrote:﻿
Reopened #236.

**Comment by mMoliere** [comment]
Firefox

**Comment by mMoliere** [comment]
I see that it looks fine in Chrome. But it would be good if you could take another look at it, because many people in the team use Firefox.

**Comment by wsalesky** [comment]
@mMoliere I made a change, it is better, but not perfect. I will leave it alone until after the presentation, then you should go back to the designers, this should be compatible in both and there are a number of differences between Chrome and Firefox it may be easier to have them resolved by the designers.
