### ISSUE TITLE
Remove excess lookup button

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#241]
@wsalesky In the bibliographical items it is distracting to have two lookup buttons. I would prefer if we only kept the one on the upper level. 
![Screenshot 2023-07-18 at 10 23 50](https://github.com/majlis-erc/manuForma/assets/73166992/8f582081-69a6-43ea-9919-cde9ba2d248a)

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/manuForma/pull/345

This is a first attempt at this feature, it may need to be refined. You can suppress a general lookup, by adding: 
`<lookup elementName="title" suppress="true"/>`

In the appropriate subform. You can also add a subform specific lookup the same way. Generic lookups can remain at the top of the config file.
