### ISSUE TITLE
Correctly hide empty input-group in new design

### ISSUE THREAD

**Issue by wsalesky** [majlis-erc/manuForma#242]
Current js hides all input groups in toolbar. Need to hide only actually empty input-group children.

**Comment by wsalesky** [comment]
@wsalesky Note to self, this is going back to the web designer for a fix.

**Comment by mMoliere** [comment]
@wsalesky In Firefox: the white boxes are still being displayed. 

In Chrome: the white boxes are gone, but this is also true for the attribute dropdowns. (And maybe related to that topic: the attribute boxes have no outlines.):
![Screenshot 2023-08-15 at 14 35 46](https://github.com/majlis-erc/manuForma/assets/73166992/15596668-9187-4fdf-bad9-e948a074cf2b)

**Comment by wsalesky** [comment]
@mMoliere I think we have 2 options here. We can go back to the designer, or we can eliminate the white boxes. I'm fine either way, but I don't think the white boxes add that much to the design.

**Comment by mMoliere** [comment]
@wsalesky Great idea! Let's get rid of the white boxes. But the dropdowns should be offset from the rest of the headline. I have played around with the CSS in the inspector: I would like the dropdowns to be inside a box with rounded edges and a solid gray border.

![Screenshot 2023-08-15 at 15 31 35](https://github.com/majlis-erc/manuForma/assets/73166992/e7765eeb-3c28-4a54-b06a-1f71fb75d1f5)

**Comment by wsalesky** [comment]
@mMoliere Sounds good to me, want to paste you css experiments into the issue?

**Comment by mMoliere** [comment]
@wsalesky The CSS instructions for the span elements containg the dropdowns are: 
```
{
background-color: white;
border: 1px solid var(--color-secondary-light);
border-radius: var(--small-radius);
}
```
But I believe that these spans need their own class to distinguish their instructions from the other span elements in the forms.

**Comment by mMoliere** [comment]
@wsalesky Ronny is very enthusiastic about these cosmetic improvements. What is the status on this?

**Comment by wsalesky** [comment]
@mMoliere I will try to get this resolved this week, today and tomorrow are being dedicated to another project with a big deadline, but I should have time Wednesday to resolve some of these remaining issues.

**Comment by mMoliere** [comment]
@wsalesky That works for me. Thanks for the info.
