### ISSUE TITLE
Person lookup behaves differently in Chrome v Firefox

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#245]
Firefox, the lookup is available:

![Screenshot 2023-07-18 at 23 10 42](https://github.com/majlis-erc/manuForma/assets/73166992/05ec8992-8d59-4897-af46-825912b16e92)

Chrome, the lookup is gone:

![Screenshot 2023-07-18 at 23 08 19](https://github.com/majlis-erc/manuForma/assets/73166992/7e0c0c80-c2d6-4fd1-89b4-ae781167ebee)

**Comment by wsalesky** [comment]
@mMoliere what subform?

**Comment by mMoliere** [comment]
@wsalesky Sorry, this is in Content description.

**Comment by wsalesky** [comment]
@mMoliere closing, as this now works on both chrome and firefox.
