### ISSUE TITLE
Error: Search doesn't work

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#259]
@wsalesky The search buttons in the Main Page menu does not yield any results and gives an error message.

**Comment by wsalesky** [comment]
@mMoliere Can you clarify what you mean by main page? of the msSimple form, the whole app? something else? A link would be great.

**Comment by mMoliere** [comment]
@wsalesky 

Result with search by ID
![Screenshot 2023-07-24 at 19 27 20](https://github.com/majlis-erc/manuForma/assets/73166992/62ff3770-0c2f-4971-a656-17ec770634ff)


Result with Search:
![Screenshot 2023-07-24 at 19 27 53](https://github.com/majlis-erc/manuForma/assets/73166992/20dd018e-668f-4996-9ed2-4f46828f19e2)

The expected result would be records containing "St Petersburg" in `title`

**Comment by wsalesky** [comment]
@mMoliere This appears to be working now?

**Comment by mMoliere** [comment]
@wsalesky The "regular" search now works.

The "Search by ID" still gives the same error message.

**Comment by wsalesky** [comment]
This should fix it: https://github.com/majlis-erc/manuForma/pull/380

**Comment by wsalesky** [comment]
@mMoliere Is this fixed?
