### ISSUE TITLE
formDesc

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#26]
The descriptions for the individual manuscript forms that are stored in the `formDesc` element in the config-mss.xml are displayed twice: Once below the header and a second time they are all displayed as one paragraph above the header. Please remove the paragraph.
![Bildschirmfoto 2022-11-09 um 12 19 52](https://user-images.githubusercontent.com/73166992/200817871-692126df-ad5f-4d2e-b06b-cd7d94a42fc9.png)

**Comment by wsalesky** [comment]
Fixed with latest merge.

**Comment by mMoliere** [comment]
No, it still doesn't work on most forms.

**Comment by mMoliere** [comment]
It does not appear to be an issue with the webhooks – If I check the files on the server in eXide, the glosses are there. What makes it even more mysterious to me is that in Hand Description and Support Description individual elements are displayed with the custom glosses. (See the example image)
![Screenshot 2022-11-15 at 11-11-35 Edit MS TEI records](https://user-images.githubusercontent.com/73166992/201893088-207a3bb9-7fc4-471b-af74-4ec776f7b70e.jpg)

**Comment by mMoliere** [comment]
Correction: The problem is present in all forms. So, it is not an isolated issue

**Comment by wsalesky** [comment]
@mMoliere The forms have not been regenerated or loaded to the server correctly. When I look at the relation forms for example, the last time it was updated was 13 days ago (https://github.com/majlis-erc/manuForma/tree/main/forms/relationTEI).

Here is a screen shot of what the updated MSS forms look like on my machine: 
<img width="1629" alt="Screen Shot 2022-11-15 at 11 26 24 AM" src="https://user-images.githubusercontent.com/1168206/201973087-4fa26471-dd63-4bdd-b982-aa1b109a69c8.png">

Would you like me to rerun all the forms and push the updated forms to github for you?

**Comment by mMoliere** [comment]
That is weird. How could I forget that? But you are right.
