### ISSUE TITLE
New feature: Warning

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#260]
@wsalesky In order to prevent merge errors it we would like a notification upon loading a record, in case the same record is already opened by someone else.

**Comment by wsalesky** [comment]
@mMoliere the pull request in github are supposed to handle any conflicts if 2 users edit the same record. If that is not sufficient, we can have users 'check out/in' documents as they edit them, that will completely lock the record from other users.

**Comment by mMoliere** [comment]
@wsalesky Yes, we would like the second option: lock the record from other users.
