### ISSUE TITLE
Automate change records

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#261]
@wsalesky At the moment the records documenting changes (`change`) are entered manually in the Admin Metadata menu. We would like to automate this. 

Our dream scenario looks like this:

Upon pushing ‘Submit to Github' a new new `change` element is created. 
The `@who` field should be filled in with the username of the logged-in team member and `@when` filled in with the date. And finally the user is receives the question: "What did you change?" and fills it manually.

Do you think we can implement this or at least part of it?

**Comment by wsalesky** [comment]
@mMoliere Yes, this is doable. Will get to work on it next week.

**Comment by mMoliere** [comment]
@wsalesky Wonderful!

**Comment by mMoliere** [comment]
@wsalesky To give you a clearer idea how we imagine this scenario from the user perspective:

1. User pushes "Submit to Github".
2. manuForma responds "What did you change?"
3. User enters his response into text field and pushes "Submit".
4. The window closes.

**Comment by wsalesky** [comment]
@mMoliere this is ready for testing. See: https://github.com/majlis-erc/manuForma/pull/311

**Comment by mMoliere** [comment]
@wsalesky I was able to test it today. I am very happy with the ease of use! 

Notes: 

1. Currently, the `change` entry is overwritten everytime a record is submitted to Github. Instead, we want to add a new entry every time.
2. I noticed that the contents of `@who` and `@when` were retained from the original change entry. `@who` should be filled with the user name of the user who is logged in and `@when` with the current date.

**Comment by wsalesky** [comment]
@mMoliere Opps! I will correct that. Also, the admin tab includes a field for a unique id that is used in the publicationStmt (example: `<idno type="URI">https://majlis.net/bibl/25DSYG9C/tei</idno>`). Where do you want this input to be? It is key to the correct functioning of the app.

**Comment by mMoliere** [comment]
@wsalesky We keep the unique ID in the admin tab. It is of no concern to most users.

Please remove the manual Changes menu from the admin tab.

**Comment by wsalesky** [comment]
Resolved with: https://github.com/majlis-erc/manuForma/pull/381
