### ISSUE TITLE
One more time: restricted elements

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#263]
@wsalesky I know that we have discussed this before. But Ronny made a suggestion that sounded workable: 

Once the schema determines that a certain element cannot be added anymore, the respective entry in the dropdown turns grey. This means it would still function, but the coloring should discourage our users from using it.

Would that work?

**Comment by wsalesky** [comment]
@mMoliere I will investigate.

**Comment by mMoliere** [comment]
@wsalesky Have you looked into this?

**Comment by mMoliere** [comment]
@wsalesky That's fine. Thanks for the update

**Comment by wsalesky** [comment]
@mMoliere Take a look at this change and let me know what you think of this functionality. 
https://github.com/majlis-erc/manuForma/pull/557
