### ISSUE TITLE
Lookup in Codicological definition finds the wrong type of records

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#268]
@wsalesky the lookup in Codicological definition should find other manuscript records. At the moment it finds bibliographic records.

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/manuForma/pull/346

**Comment by wsalesky** [comment]
@mMoliere So it should return a title with a ref?

**Comment by mMoliere** [comment]
Indeed this is the same as #268
