### ISSUE TITLE
Summary text window is too narrow

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#269]
@wsalesky In content description, the summary text window is strangely very narrow. Other fields are usually broader. This is especially unfortunate, since this field invites verbose descriptions.
![Screenshot 2023-07-25 at 12 48 20](https://github.com/majlis-erc/manuForma/assets/73166992/e2ebe39b-de6a-4a5a-a46d-a093428b5d42)

**Comment by wsalesky** [comment]
Fixed.  https://github.com/majlis-erc/manuForma/pull/312
