### ISSUE TITLE
Custom button text

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#270]
@wsalesky For the repeatable collapsibles there is a button that allows us to create another collapsible of the same type. Sofar, this button merely repeats the description of the collapsible. We would like the button to have more a more expressive text. 

Example: In the example below we would like to read "Add detailed description …"

![Screenshot 2023-07-25 at 12 51 06](https://github.com/majlis-erc/manuForma/assets/73166992/eb4f0a4e-25d4-4b0a-a201-28986985494d)

**Comment by wsalesky** [comment]
@mMoliere Do you want me to simply include 'Add' for all of the buttons, or do you want to have someway to have a different  text for each button. (The first option is very simple, the second not so much.)

**Comment by mMoliere** [comment]
@wsalesky Let's do the simple solution. And please put the name after "Add" into quotation marks.

E.g.  + Add "Detailed description of text unit …"

**Comment by wsalesky** [comment]
Update available. If it looks good, close the issue.
