### ISSUE TITLE
Move Lookup button

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#275]
@wsalesky We have simplified the template somewhat. In content description `msItem/author/persName` has become `msItem/author`. But this means that the lookup button has to be moved one level up in the hierarchy to `author`.
![Screenshot 2023-07-25 at 16 42 21](https://github.com/majlis-erc/manuForma/assets/73166992/687ad519-636a-4edd-9b02-1be8f2a92101)

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/manuForma/pull/346
