### ISSUE TITLE
Error: Content of Dropdown displayed in text field

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#276]
@wsalesky In Page layout, summary/desc has a dropdown list of controlled values. However, when an item is selected manuForma displays both the dropdown and a text field containing the same string. This is confusing to the users. Moreover, if the content of text field is manipulated the selection in the dropdown is emptied.
![Screenshot 2023-07-26 at 13 00 44](https://github.com/majlis-erc/manuForma/assets/73166992/e1d3d03e-87b4-4358-bf4c-4035a1e74461)

Addendum: the same is happening in Text layout.

**Comment by wsalesky** [comment]
@mMoliere fixed by v1.23. Please test and close if it solves the issue.

**Comment by mMoliere** [comment]
@wsalesky Yes, that worked beautifully!
