### ISSUE TITLE
Restricted attributes

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#280]
@wsalesky It would be convenient if we could signal that certain attributes have a fixed value and that users need not concern themselves with it. This could be a grey background or something similar. In the schema, `attDef` could take the attribute `@style="restricted"`

For instance in //objectDesc/supportDesc/extent/measure/@unit
![Screenshot 2023-07-26 at 13 09 59](https://github.com/majlis-erc/manuForma/assets/73166992/6a2b52aa-3216-46eb-841a-6d48196ca1c7)

**Comment by wsalesky** [comment]
@mMoliere that sounds good. Let me know when there is a schema with this attribute for me to test.

**Comment by mMoliere** [comment]
@wsalesky will do

**Comment by mMoliere** [comment]
I have added this to one of the schemas:

https://github.com/majlis-erc/manuForma/blob/3feb48a5eaaa0c6b65935e877cd08ce77b2482ac/forms/schemas/mss-support.xml#L605

**Comment by wsalesky** [comment]
Note to self, maybe use xf:hint? Can not add a style directly, may have to resolve when resolving xf:bind issues.

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/manuForma/pull/463
