### ISSUE TITLE
Unite attribute and element dropdown?

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#297]
@wsalesky The users struggle with having two selection dropdowns next to the element name. The distinction between attribute and child-element means has no meaning in the context of the user interface. So they rightly ask, if it is possible to unite everything into one dropdown.

If that is not possible, they would prefer the child-elements to be listed before the attributes.

![Screenshot 2023-07-26 at 16 20 27](https://github.com/majlis-erc/manuForma/assets/73166992/6a9d23a8-a44f-4810-9ddf-23b603816b0a)

**Comment by wsalesky** [comment]
@mMoliere I agree, it is confusing, any chance you would consider renaming the attributes dropdown? You could call them 'elements' and 'features' (if attribute does not make sense). Unfortunatly they can not be combined as they are structurally 2 different parts of the XML.

**Comment by mMoliere** [comment]
@wsalesky Yes, I thought as much. 

So, elements stay "fields" and attributes become "features", and you switch the order?

**Comment by wsalesky** [comment]
@mMoliere Yes, that sounds good to me.

**Comment by wsalesky** [comment]
@mMoliere See pull request : https://github.com/majlis-erc/manuForma/pull/307
