### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#299]
@wsalesky The logo is not the version, we agreed on. I can't check the .xar file Nicolas sent us, because the link expired. 

Could you check if the .xar contains this logo and change it? Otherwise I will ask Nicolas.

![Screenshot 2023-07-27 at 20 18 43](https://github.com/majlis-erc/manuForma/assets/73166992/b6c3adc0-6203-4aca-9e42-a590efd95064)

**Comment by wsalesky** [comment]
@mMoliere it is not in the files I have. Just this one: 
![logo_manuforma](https://github.com/majlis-erc/manuForma/assets/1168206/20d0fb09-c718-4f20-857e-d8a71c20aabb)

**Comment by mMoliere** [comment]
@wsalesky Thanks!
