### ISSUE TITLE
How to add attribute values to collapsible headline?

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#329]
@wsalesky I have tried different XPaths, but I can seem to be able to add the values from attributes to the headlines of collapsibles. Is it only possible to add element values or am I overlooking something?

**Comment by wsalesky** [comment]
@mMoliere Can you tell me what you have tried, and what you want to see so I can do some testing?

**Comment by mMoliere** [comment]
@wsalesky 

One thing I have tried is this:

```
<group groupLabel="Codicological definition." groupLabelConditionalElement="./*" groupLabelXPath="concat('Codicological definition: ', ./*, ./*@rend, ./*@style)" groupNo="1" repeatable="no">
                    <element xpath="tei:objectType"/>
</group>
```

The result would display the following:

 "Codicological definition: Single manuscript square codex"

So far, I can only display  "Codicological definition: Single manuscript".

**Comment by wsalesky** [comment]
@mMoliere Your xpath is incorrect. Try this instead:

`<group groupLabel="Codicological definition." groupLabelConditionalElement="./*" groupLabelXPath="concat('Codicological definition: ', ./*,' ',./*/@rend,' ',/*/@style)" groupNo="1" repeatable="no">`

**Comment by wsalesky** [comment]
@mMoliere Can this be closed?
