### ISSUE TITLE
Small Change: Symbol

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#33]
I noticed in the look-up menu that the same symbol is used for the "Lookup" and "New Title/Person/Place" buttons. Please assign a different symbol to the latter, like "+".

**Comment by wsalesky** [comment]
@mMoliere Can you add a screen shot for clarity? Thanks!

**Comment by wsalesky** [comment]
Fixed. (Will push new forms when I fix all the other small bugs. )
