### ISSUE TITLE
Merge problem

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#348]
@wsalesky It seems your latest commits have overwritten changes that I made. I think this may be the same problem that we have encountered in the Bibliography subform where an obsolete version re-emerged.

I noticed in the config where file I had rewritten the Reproductions subform from this:

https://github.com/majlis-erc/manuForma/blob/c8c1d961077ab5768ace72e8a63f6ad3eeb7c144/forms/formGenerator/config.xml#L178C9-L187C28

To this:

https://github.com/majlis-erc/manuForma/blob/2559943f2581f4451468652b7cc7cbaf89effd7e/forms/formGenerator/config.xml#L181C1-L193C2

When I opened the file this morning after committing your changes, I noticed the difference. I dug into the differences and I discovered that other parts of the config were also reverted to the previous state. https://github.com/majlis-erc/manuForma/commit/be88b5f1834bf7dc3710c5f1c971093f1f5c8437#diff-430398f709c4fc2f00a9ebca5bd7840552f683756e683dff281d8c4b59749cbd

Is there a efficient way to merge my changes with your changes?

Is there something we can do to prevent this in the future?

**Comment by wsalesky** [comment]
@mMoliere Hum. I try to pull the master branch before every change, I wonder if I missed that step. I will be more careful in the future.
