### ISSUE TITLE
Remove Look-Up from Header

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#35]
In all record types: please remove the lookup feature from the submenu "Header". It does not make sense at this place.

**Comment by wsalesky** [comment]
@mMoliere I will need some sort of TEI rule to base this on. Should I make it so the lookups do display for the whole teiHeader element? Or just the titleStmt?

**Comment by mMoliere** [comment]
@wsalesky Disable the lookup for `titleStmt`
