### ISSUE TITLE
Bug: Manuscript join

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#373]
@wsalesky The lookup links to the desired kind of records. Thank you!

There is only a small problem. Whenever a record is added, the `listBible` and `bibl` elements are duplicated.

In the image image below the TEI structure is `listBibl/listBibl/bibl/bibl.` What we want is `listBibl/bibl.`
![Screenshot 2023-08-09 at 17-46-15 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/caf7a4c1-d6b5-4af5-8388-288d15528888)

**Comment by wsalesky** [comment]
@mMoliere Thanks for testing, I will take a look and check to see what is going on, probably inserting the wrong element and getting a nested bibl.

**Comment by wsalesky** [comment]
@mMoliere This should be resolved. Although I noticed, there is no idno displaying, perhaps there is no idno defined in the schema for the bibl element?
