### ISSUE TITLE
Add description to submit window

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#389]
@wsalesky We would like brief instruction in the window that opens upon clicking "Submit":
![Screenshot 2023-08-28 at 12-03-27 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/05da2521-6bed-41f5-b083-df7a8b3beeb7)

**Comment by mMoliere** [comment]
@wsalesky "Write a one-sentence description of the changes you made to the file."

**Comment by wsalesky** [comment]
Resolved with: https://github.com/majlis-erc/manuForma/pull/413
