### ISSUE TITLE
Changes submitted on manuForma don't arrive on Github

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#395]
@wsalesky While manuForma confirms that the changed file has been submitted, there is no pull request when I check the repository. A glance at the webhook configuration shows that there was a problem with changes to XML files that I submitted yesterday from my local computer. Could this be the cause? I tried it with 6 out of 12 files and they all failed.

**Comment by wsalesky** [comment]
@mMoliere The app is not authenticating. You will need to provide your credentials here: 
https://github.com/majlis-erc/manuForma/blob/main/services/git-commit.xql#L48

Or if you prefer, you can get the credentials set up as a server variable and then we can call that variable from the script. 

It seems to me that the credentials are getting erased somehow? Maybe when the app is updated? So a server variable might be easier to persist.

**Comment by mMoliere** [comment]
@wsalesky I am in favor of a durable solution. Can you give me a step-by-step guide for setting up the server variable?

**Comment by mMoliere** [comment]
@wsalesky Will do. Thank you!
