### ISSUE TITLE
Lookups behaving in unexpected ways

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#400]
@wsalesky The lookups for the entities title, person and place are missing buttons, or display white windows.
I have tried to fix this in the config. But since I don't know what all the parameters mean, I didn't achieve anything.

Here is an example from Content description where buttons are missing:
![Screenshot 2023-08-29 at 20 54 23 copy](https://github.com/majlis-erc/manuForma/assets/73166992/e980be73-214b-4809-871b-f129eac7a08d)

And here is a complete list of the errors:

# Content description

- Canonical title (`title`): Lookup missing
- Canonical author name (`author`):  "Add New Person" missing

# Physical description: writing material

- Place of origin (`origPlace`):  "Add New Place" missing

# Physical description: script/hand description

- Person (`persName`): Lookup missing
- Place of origin (`origPlace`):  clicking Lookup opens white window

# Incodicated documents

- Person (`persName`): Lookup missing

# History

- Person (`persName`): Lookup missing
- Place of origin (`origPlace`):  clicking "Lookup" opens blank window

**Comment by mMoliere** [comment]
@wsalesky For author we want: `<author ref="https://majlis.net/person/15">ʿAlī ben Abraham al-Ṭawīl (Ramla)</author>`

Incodicated document has a `persName` element in the template (https://github.com/majlis-erc/manuForma/blob/4390d6d1a7653b163a997a1bbf47303337280c10/forms/templates/full-mss-template.xml#L182C42-L182C42) – or do you mean in the config? I only added the lookup element in the config when I wanted to diverge from the original usage. e.g. apply person to `author` instead of `persName`. Did I misunderstand the use?

**Comment by wsalesky** [comment]
@mMoliere Thanks! The template was what I needed. I'm testing this today, hope to solve the issue by the end of the day. You are using the config correctly, the XSLT was interpreting it incorrectly. I'm working on a solution that will allow everything we want.

**Comment by mMoliere** [comment]
@wsalesky Sounds great. Thank you!

**Comment by wsalesky** [comment]
@mMoliere Sorry, that one took forever to figure out! Fix is on this pull request: 
https://github.com/majlis-erc/manuForma/pull/419

**Comment by mMoliere** [comment]
@wsalesky That's OK, we have time. Thanks for the great work!

**Comment by mMoliere** [comment]
@wsalesky I have merged your changes into the app. It works in some fields, but not in all:

# Content description

[ ] - Canonical title (`title`): Lookup missing
[ ] - Canonical author name (`author`):  "Add New Person" missing

# Physical description: writing material

[ ] - Place of origin (`origPlace`):  "Add New Place" missing

# Physical description: script/hand description
 
[ ] - Person (`persName`): Lookup missing
[ ] - Place of origin (`origPlace`):  clicking Lookup opens white window

# Incodicated documents

[ ] - Person (`persName`): Lookup missing

# History

[ ] - Person (`persName`): Lookup missing
[ ] - Place of origin (`origPlace`):  clicking "Lookup" opens blank window

**Comment by wsalesky** [comment]
@mMoliere Can this be closed?

**Comment by wsalesky** [comment]
@mMoliere Checking in to see if this can be closed?
