### ISSUE TITLE
Modify URI

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#402]
@wsalesky In the headline of the app next to the name of the ms we display the URI, e.g. [https://majlis.net/person/3/tei].

 We would like to modify this. Is it possible to only a display part of it, like this [person/3]?

**Comment by wsalesky** [comment]
@wsalesky note to self, this does not seem to be working. Using replace() in xf:output

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/manuForma/pull/461
