### ISSUE TITLE
New feature: Allow subforms based on attribute value

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#412]
@wsalesky For the persons forms we would like to subdivide the template into subforms. The problem is that most elements can only be used as child elements of `person`. 

This is what the template looks like now:

person:
- persName
- birth
- death
- floruit
- bibl
- idno

My plan to get around this limitation is to have type attributes that can be used to generate subforms for names, biographical data, etc.

person/@type="names":
- persName

person/@type="bio":
- birth
- death
- floruit
 
person/@type="bibl":
- bibl

person/@type="idno":
- idno

In the config, the xpath for each subform would look like this:` /tei:TEI/descendant::tei:listPerson/tei:person/tei:@type='bio'`

However, `generateXForm.xsl` does not allow attributes in the XPath. Is that something that can be added?

I have tried to come up with another way to formulate the template, but what gets in the way everytime is the limitations placed on birth, death, floruit etc.

Subdividing the persons module of manuForma is very important to the team.

**Comment by mMoliere** [comment]
@wsalesky Thanks for the quick reply. It was worth a try, but the answer is always "Invalid element name."

**Comment by wsalesky** [comment]
@mMoliere I will take a look. Still trying to figure out the odd lookup window behavior.

**Comment by wsalesky** [comment]
@mMoliere Cant you do something similar to how the manuscripts are broken up? For example like this: 

```
<elementGroups>
                <group groupLabel="Names" groupNo="1" repeatable="no">
                    <element xpath="tei:persName"/>
                </group>
                <group groupLabel="Bio" groupNo="2" repeatable="no">
                    <element xpath="tei:birth"/>
                    <element xpath="tei:death"/>
                    <element xpath="tei:floruit"/>
                </group>
                <group groupLabel="Bibl" groupNo="3" repeatable="no">
                    <element xpath="tei:bibl"/>
                </group>
            </elementGroups>
```

**Comment by wsalesky** [comment]
@mMoliere Checking back in on this. I think this functionality already exists. If not, can you post the code you have tried?

**Comment by mMoliere** [comment]
@mMoliere It is not sufficient to break the person template into collapsibles. It is still very cluttered.

The functionality does not exist.

This is the error message:

> Invalid element name. Invalid QName {id='names'}

This is an example of how one section in the config looks like:

```
<subform xpath="/tei:TEI/descendant::tei:listPerson/tei:person/@xml:id='names'" formName="names" formLabel="Names">
            <formDesc>Personal name(s).</formDesc>
            <localSchema src="../schemas/persons.xml"/>
            <globalSchema src="../schemas/mss-compiled.odd"/>
            <xmlTemplate src="../templates/persons-template.xml"/>
            <elementGroups>
                <group groupLabel="Personal name." groupLabelConditionalElement="./*:name | ./*:addName | ./*:forename" groupLabelXPath="concat(./*:name, ' ', ./*:forename, ' ', ./*:addName[1], ' ', ./*:addName[2], ' ', ./*:addName[3], ' ', ./*:addName[4], ' ', ./*:addName[5], ' ', ./*:addName[6], ' ', ./*:addName[7], ' ', ./*:addName[8], ' ', ./*:addName[9], '(',./@type, ' name)')" groupNo="1" repeatable="yes">
                    <element xpath="tei:persName"/>
                </group>
            </elementGroups>
        </subform>
```

And this is the relevant portion from the template:

```
<person xml:id="names">
            <persName xml:id="name$$$-1" xml:lang="he-Latn" type="majlis-headword" source="bibl$$$-$" resp="">
                <name/>
            </persName>
            <persName xml:id="name$$$-2" xml:lang="ar-Latn" type="majlis-headword" source="#bibl$$$-$" resp="">
                <name/>
            </persName>
        </person>
```

**Comment by wsalesky** [comment]
@mMoliere I do not see the above person element in the template? Can you update the persons-fulltemplate.xml to reflect this, so I can test it? Thanks!

**Comment by mMoliere** [comment]
@wsalesky Done

**Comment by wsalesky** [comment]
@mMoliere Checking on on this, is it working as you want?
