### ISSUE TITLE
Add "Definition of script." not working

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#423]
@wsalesky The Add "Definition of script." button in Physical description: script/hand description is not working. When it is clicked there is no reaction. No new collapsible is created.

**Comment by wsalesky** [comment]
@wsalesky Note to self, this is because it is a nested element (more tricky than if it were a direct child)

path: tei:scriptDesc/tei:scriptNote
full path: /tei:TEI/descendant::tei:msDesc/tei:physDesc + tei:scriptDesc/tei:scriptNote

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/manuForma/pull/428

**Comment by mMoliere** [comment]
@wsalesky Thank you for the great work! It works really well.

There is now only one small issue: Whenever a new `scriptDesc` is created in manuForma it is the first child element of physDesc – However this creates non-valid code, because the TEI requires the `ab` element to come first.

https://github.com/majlis-erc/majlis-data/blob/84111b487919c90e0d2ca99e558abcd917797d4b/data/manuscripts/tei/4.xml#L116C26-L121C17

Is it possible to put any newly created `scriptDesc` behind the `scriptDesc` that is already in the file?

**Comment by wsalesky** [comment]
@mMoliere solved with this pull request: 
https://github.com/majlis-erc/manuForma/pull/440
