### ISSUE TITLE
New feature: select @source from dropdown

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#425]
@wsalesky We anticipate that we will be using many of the Zotero entries that are already available through the lookup in the Persons form. We would like to streamline the way these information are referenced. manuForma already assigns @xml:ids to the <bibl> elements.

We envision that these ids be available for referencing in the @source attributes of <persName>, <birth>, <death> etc. in the form of a dropdown or something that is equally accessible.

The workflow could look something like this:

1. The user adds the information from a Zotero entry to a <bibl> using the lookup feature.
2. The user add the id to that Zotero to persName/@source from a dropdown.

Bonus: the high-end version of this feature would display the <title> of the referenced <bibl> while adding the xml:id to the TEI in the background.

Here are some mockups:

![source-1](https://github.com/majlis-erc/manuForma/assets/73166992/faab3e75-765e-4bc5-83b5-e1ea3d507c98)
![source-2](https://github.com/majlis-erc/manuForma/assets/73166992/2b11e4d5-724b-4283-a974-ce2fe9eb2638)

**Comment by wsalesky** [comment]
First try here: https://github.com/majlis-erc/manuForma/pull/483

**Comment by wsalesky** [comment]
@mMoliere any reviews on this?

**Comment by mMoliere** [comment]
@wsalesky Works beautifully!
