### ISSUE TITLE
Urgent: "Submit Error"

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#438]
@wsalesky manuForma displays an error message when selecting an existing record via "Browse", "Search" and "Search by ID".

> Submit error. 

The webhooks all look fine. I am puzzled.

The matter is time sensitive – there is a presentation of the tool on Thursday.

**Comment by wsalesky** [comment]
@mMoliere So sorry! I am looking into it now.

**Comment by mMoliere** [comment]
@wsalesky You are the best!

**Comment by wsalesky** [comment]
@mMoliere Sorry I didn't get to it sooner!
