### ISSUE TITLE
Prettify the URI

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#448]
@wsalesky The users have asked to modify the URI into something prettier: In particular they want to remove the "/tei" from e.g. "https://jalit.org/manuscript/4/tei" I believe that this should be doable, right?

Paths need to be modified in various apps and the extant files, but I don't want to miss something and break the entire ecosystem. What would be a sensible way to go about this?

**Comment by wsalesky** [comment]
@mMoliere Yes that is doable. I will need to make one small change in the Srophe app code base. I will do that tonight, so it will be ready any time you want to make the change.

**Comment by wsalesky** [comment]
Resolved here: https://github.com/majlis-erc/srophe/issues/71
