### ISSUE TITLE
New Feature: Dropdown For Element Content

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#45]
@wsalesky Another request from the team: They want to be able to create consistent metadata in the msIdentifier subform. To that end, they want the ability to select the name of library, its city, country etc. from dropdown lists.

The elements in question are: country, settlement, institution, and repository,

I could provide a list for each if this seems feasible to you.

**Comment by wsalesky** [comment]
Is there a way to add these controlled vocabulary to the schema? If not we can add them to the config.xml files. Let me know what you think, it should be pretty easy to add.

**Comment by mMoliere** [comment]
To my knowledge you can only define lists of attribute values in the schema.

List of values:

`country`:

Russia
USA
England
Israel
Hungary
France

`institution`:

National Library of Russia
British Library
Ben Zvi Institute
Library of the Hungarian Academy of Sciences
Cambridge University Library
National Library of France
Alliance Israélite Universelle
Jewish Theological Seminary

`settlement`:

St. Petersburg
London
Jerusalem
Budapest
Cambridge
Paris
New York

`repository`:

Kaufmann

**Comment by wsalesky** [comment]
Okay, in that case I am going to add it to the config.xml file. This will make the config.xml file bigger, but I think that is okay.

**Comment by mMoliere** [comment]
Excellent, that will also make it convenient to expand if needed.

**Comment by wsalesky** [comment]
Note to self, done. Will update all forms when all bugs have been addressed.

**Comment by mMoliere** [comment]
@wsalesky The dropdowns worked fine last week. Now they have vanished. Is this maybe connected to the merging of branches last week?

**Comment by wsalesky** [comment]
@mMoliere Did you rerun the forms? 
This file looks like it was overwritten sometime in the past 2 hours: 
https://github.com/majlis-erc/manuForma/blob/main/forms/formGenerator/config.xml

The correct version of the file is here: 
https://github.com/majlis-erc/manuForma/blob/development/forms/formGenerator/config.xml

As you can see the controlled values are missing from the version on the main branch. 
I'm not sure where that merge mistake happened. But if you replace the version on main with the version on the development branch you should be good.

**Comment by mMoliere** [comment]
@wsalesky Yes, I reran the forms. Thank you for pointing me to the correct version!

**Comment by wsalesky** [comment]
It is easy to overwrite on github. A good strategy is to always pull from the main branch before you start work, and then do your work on a new branch of the latest main branch, then merge back in when you are done.

**Comment by mMoliere** [comment]
That's good advice. But now I am having merge conflicts between my files and the development branch. Even the files generated by the forms generator have dozens little changes that GitHub wants me to manually resolve. My hunch is that something is going wrong. Please help!

**Comment by mMoliere** [comment]
My attempts to resolve the merge issues has had the side effect that the generator is not working anymore.

**Comment by wsalesky** [comment]
@mMoliere I will take a look. Please do not use the development branch. I use it to develop the forms. The process you would want to use is: 
1. Checkout the main branch
2. Fetch any changes to make sure you are up to date
3. Check out a new feature branch off of the main branch to do your work on
4. Do your work and then merge it into the main branch. 

I recommend doing this is small steps, so make a single change for each branch. The important files to protect are going to be in these directories: 
https://github.com/majlis-erc/manuForma/tree/main/forms/formGenerator
https://github.com/majlis-erc/manuForma/tree/main/forms/schemas
https://github.com/majlis-erc/manuForma/tree/main/forms/templates

Everything else get automatically generated every time you run the form generator. So my strategy is run a single form for each branch, and make sure my generated for files replace what is on the main branch, you do not want to merge any files within https://github.com/majlis-erc/manuForma/tree/main/forms/mssTEI (for example), because the new ones should completely replace the old ones. 

I will run a new version of the mssTEI forms, and make sure the formGenerator files are all correct. I will let you know when things are back on track.

**Comment by wsalesky** [comment]
@mMoliere I resolved the merge conflicts and reran the MS forms. Can you tell me how it looks now? 
Thanks

**Comment by mMoliere** [comment]
You're amazing! But GitHub still does not allow me to switch back to the main branch on my computer. Is it may be best to disconnect the folder on my folder and create a new copy with files pulled from Github?

**Comment by wsalesky** [comment]
@mMoliere Not to worry, you can get your local repository back on track. If you are still in the midst of a merge, you can use: git merge --abort  or to reset your local branch you can use: git reset --hard HEAD

**Comment by wsalesky** [comment]
If you are still stuck you can just switch to a new folder and re-pull the repository. Generally there is a way around that though. :)

**Comment by mMoliere** [comment]
Thank you for your help!

**Comment by mMoliere** [comment]
@wsalesky Ronny and Gregor suggested that the dropdowns in msIdentifier filter the content of the subordinate fields. e.g. for the selection of `country` "Russia" it is only possible to select in `settlement` the value "St. Petersburg" and in `institution` it is only possible to select "National Library of Russia". 

Is that feasible?

**Comment by wsalesky** [comment]
@mMoliere Is there some language in the schema that can connect values in this way? I will need some way to create a rule between them.

**Comment by wsalesky** [comment]
@mMoliere can this be closed?

**Comment by mMoliere** [comment]
@wsalesky There is a taxonomy that fits the bill. However, it would have to be situated in the preamble of the ODD.

Would something like this work?

```
<taxonomy xml:id="tax.b">
 <bibl>Brown Corpus</bibl>
 <category xml:id="tax.b.a">
  <catDesc>Press Reportage</catDesc>
  <category xml:id="tax.b.a1">
   <catDesc>Daily</catDesc>
  </category>
  <category xml:id="tax.b.a2">
   <catDesc>Sunday</catDesc>
  </category>
  <category xml:id="tax.b.a3">
   <catDesc>National</catDesc>
  </category>
  <category xml:id="tax.b.a4">
   <catDesc>Provincial</catDesc>
  </category>
  <category xml:id="tax.b.a5">
   <catDesc>Political</catDesc>
  </category>
  <category xml:id="tax.b.a6">
   <catDesc>Sports</catDesc>
  </category>
 </category>
 <category xml:id="tax.b.d">
  <catDesc>Religion</catDesc>
  <category xml:id="tax.b.d1">
   <catDesc>Books</catDesc>
  </category>
  <category xml:id="tax.b.d2">
   <catDesc>Periodicals and tracts</catDesc>
  </category>
 </category>
</taxonomy>
```

**Comment by wsalesky** [comment]
@mMoliere I do not see a way to connect the drop downs as requested. Do you want to close this or leave it open for future development?
