### ISSUE TITLE
Remove "Account" button

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#451]
@wsalesky Underneath the username a button labelled as "Account" is displayed. This does not appear to have a function. Please remove it.
![Screenshot 2023-10-25 at 14 33 35](https://github.com/majlis-erc/manuForma/assets/73166992/d650ebfe-d21c-4435-8376-52a3e51ef70d)

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/manuForma/pull/453

This button is supposed to make a list of all records edited by the current user. The functionality is not built yet, but should not take much time, if this is something you think would be useful.

**Comment by mMoliere** [comment]
@wsalesky That will be a usefull feature once it's finished. Today it caused some confusion.
