### ISSUE TITLE
Persons config does not compile

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#458]
@wsalesky The persons config does not compile as it should. It just keeps on processing. With my limited debugging skills I have found that the XSLT works until this point: 

https://github.com/majlis-erc/manuForma/blob/0aa210d4d4c71bce3cb092a7934171ce8f16a27a/forms/formGenerator/generateXForm.xsl#L405

I have made some additions to the config, but it does not compile even when I comment the added sections.

**Comment by wsalesky** [comment]
I will take a look, usually this happens if there is an element that calls itself endlessly. On Nov 20, 2023, at 12:30 PM, mMoliere ***@***.***> wrote:﻿
Assigned #458 to @wsalesky.

**Comment by wsalesky** [comment]
@mMoliere Your copy does not match the version I used for testing. 
My copy:  https://github.com/majlis-erc/manuForma/pull/459

Please use this format to generate the subforms.

**Comment by mMoliere** [comment]
@wsalesky I tried your format and it also does not work

**Comment by wsalesky** [comment]
@mMoliere I will investigate.

**Comment by wsalesky** [comment]
@mMoliere It is failing on this element https://github.com/majlis-erc/manuForma/blob/main/forms/schemas/person-schema.xml#L191

The tei:ab element needds to be defined in the schema, or removed from the person element. I removed it and the config ran as expected. Let me know how it goes on your end.

**Comment by mMoliere** [comment]
@wsalesky But it is defined in the schema: https://github.com/majlis-erc/manuForma/blob/390730a05bcd5abf0272b325c3563cf27fb1a554/forms/schemas/person-schema.xml#L981

or am I missing something here?

**Comment by wsalesky** [comment]
Oh, my bad. You are right, it is defined in the schema. So it must be something else, connected to this element. I will do some more checking. Sorry about that.

**Comment by wsalesky** [comment]
@mMoliere Can you try running the new version of config-persons-demo.xml ? Let me know if that works as you expect.

**Comment by mMoliere** [comment]
@wsalesky I'm afraid that's not working.
