### ISSUE TITLE
Add Credits to Admin Metadata

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#466]
@wsalesky Please add the changelog to the Admin Metadata section.
![Screenshot 2023-11-28 at 15-38-01 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/e22ffcf0-5ac4-46f8-ab41-6819aceb2696)

**Comment by wsalesky** [comment]
@mMoliere Do you want this to just display the change log, or allow editing?

**Comment by mMoliere** [comment]
@wsalesky Just display it.

**Comment by wsalesky** [comment]
Resolved here: https://github.com/majlis-erc/manuForma/pull/473
