### ISSUE TITLE
Larger transcription fields

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#467]
@wsalesky Is there a way to enlarge the transcription fields in the Incodicated documents subform? We anticipate that we will have a great number of lengthy quotations. The trouble is that the field is too narrow to display them in their entirety.

Some fields are already larger. Like the note field immediately following the transcription. What is the rationale for the size? Does manuForma assign the size based on the presence or absence of attributes?

![Bildschirmfoto 2023-11-28 um 15 59 32](https://github.com/majlis-erc/manuForma/assets/73166992/6a7fdd5b-c664-40fc-a459-49b4b4445d82)

**Comment by wsalesky** [comment]
@mMoliere Currently manuForma uses textarea elements for a small list of elements: ('p','desc','note','summary')

I can expand that list if you want. Or we can indicate it in the schema with an attribute if you prefer. Either works for me.

**Comment by mMoliere** [comment]
@wsalesky Got it! Please add "quote" to that list

**Comment by wsalesky** [comment]
Added here: https://github.com/majlis-erc/manuForma/pull/472
