### ISSUE TITLE
Text editor for manuForma?

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#468]
@wsalesky In the team, there is demand for a text editor inside manuForma to edit quotations. This editor would be able to wrap text inside elements in the same way one would markup bold text in MS Word.

To me this idea runs counter to the way manuForma works, since it is designed to display every element in its own field.

But maybe there is a way to designate elements that manuForma could display including the child elements?

What do you think?

**Comment by wsalesky** [comment]
@mMoliere I can investigate. We would have to restrict it to specific elements. Paragraphs? Notes? Quotes? I'm sure you have a list. Let me do a small test to see if it is even possible.

**Comment by mMoliere** [comment]
@wsalesky The only instant where this would be of use is the `quote` element. As a start, it would be helpful to add the `lb` element.

**Comment by mMoliere** [comment]
@wsalesky The text editor has become a priority now. I did not anticipate that the team wants to use headings, cursive text and multiple paragraphs in their notes. Have you found out if this is at all possible?

**Comment by wsalesky** [comment]
@mMoliere I'm testing now. First try did not yield anything workable, but I have not given up yet. I will keep you posted.

**Comment by wsalesky** [comment]
@mMoliere I have a question out to the XForms list on this feature, waiting to hear back. So far this is not possible on our forms.

**Comment by mMoliere** [comment]
@wsalesky Thank you for the update. This is still on the top of our priorities list.

**Comment by wsalesky** [comment]
@mMoliere an update. I am making some progress with this. I will need to work on post processing the results, but I hope to have something for testing by the end of next week.

**Comment by mMoliere** [comment]
@wsalesky This is great news! Thank you

**Comment by mMoliere** [comment]
@wsalesky Is there any news in this matter?

**Comment by mMoliere** [comment]
@wsalesky Can you tell me about your progress?

**Comment by wsalesky** [comment]
@mMoliere I just checked in with Alain, hopefully he will be able to get me a fix ASAP as it sounded like he had something pretty much ready to go. I will let you know as soon as I hear from him.

**Comment by wsalesky** [comment]
@mMoliere So far all the fixes offered by the XSLTForms have not solved the bug in the text editor option. We are still going back and forth, but this may not be something that can be achieved with our forms.

**Comment by mMoliere** [comment]
@wsalesky I figured this was a complicated task. Out of curiousity and to understand how we might proceed, how did you try to implement the editor options? Using XForms exclusively, incorporating an external framework like Quills?

**Comment by wsalesky** [comment]
@mMoliere The way the XSLTForms work is the HTML page is converted via XSLT and Javascript, this means I can not just plug in any old text editor, as the Javascript from the XSLTForms code will not transform it correctly. There is a plug in to allow the use of the tinyMCE editor, unfortunatly it does not work with forms as complicated as ours. The nested repeats are causing all sort of bugs, these have to be addressed on the XSLTForms code base before we can use it, and our use case is out of the norm. I can post a version with the text editor included so you can see the issue for yourself if you would like.

**Comment by mMoliere** [comment]
@wsalesky Thank you, that's interesting. 

I have cooked up an idea but I don't know if it is feasible or if it would run into the same problem you described:

What if users encode their markup to `note` elements as Markdown which manuForma then transforms into TEI elements before the file is submitted to Github? Whenever the file is reopened in manuForma, the TEI inside the `note` element is again transformed into Markdown, so that the text can be edited again.

For example:

```
<note>I really like using *Markdown*.

I think I'll use it to format all of my documents from now on.</note>
```

Becomes:
```
<note><p>I really like using <emph>Markdown</emph>.</p>
<p>I think I'll use it to format all of my documents from now on.</p></note>
```

There are stylesheets in the TEI projects that could be used as starting point. The question is whether these transformations could be integrated into manuForma.

**Comment by wsalesky** [comment]
@mMoliere This is an interesting idea. I think it would be best if we could make it a very limited set of markdown, though, to keep it as simple as possible. I will test it after I get the relationship lookup working.

**Comment by mMoliere** [comment]
@wsalesky That sounds promising! 

I think we can do with a small set of tags:

`<p>`, `<lb>`, `<emph>` should cover most of our requirements.

**Comment by mMoliere** [comment]
@wsalesky Have you had a chance to test this idea?

**Comment by wsalesky** [comment]
@mMoliere I have not had a chance to test this yet. I will try to get to it early next week.

**Comment by mMoliere** [comment]
@wsalesky Please do

**Comment by wsalesky** [comment]
@mMoliere Please test this: https://github.com/majlis-erc/manuForma/pull/624

Keep in mind it only allows paragraphs, line breaks and *em* in markdown. And only on summary, desc, note, quote and p elements.

**Comment by mMoliere** [comment]
@wsalesky It works really well! Thank you!

**Comment by wsalesky** [comment]
@mMoliere Great! I'm glad we were finally able to get this working.
