### ISSUE TITLE
Superfluous commas in collapsibles

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#488]
@wsalesky Some collapsibles display values from multiple fields separated by commas. The problem is that when one or more fields have not been filled out lonesome commas are being displayed. E.g. in in the codicological definitions:

 
<img width="1438" alt="Bildschirmfoto 2023-12-22 um 19 02 57" src="https://github.com/majlis-erc/manuForma/assets/73166992/5a972e89-7379-4151-81eb-95a18cffcc2e">

I tried to write a more sophisticated XPath to tackle this problem, but I could not get it to work.

**Comment by wsalesky** [comment]
@mMoliere More complex XPath are not allowed here, the XForms processor will not be able to process them, so  sadly the lonesome commas are unavoidable.

**Comment by mMoliere** [comment]
@wsalesky Noted. Thank you!
