### ISSUE TITLE
New Feature: Additional Explanation paragraph

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#49]
@wsalesky Ronny suggested that we add another way to explain the use of fields to users: One paragraph below the field name and its attributes. This paragraph would take the contents of another `<desc @type="blurb">`. I can provide a sketch if neccessary.

**Comment by wsalesky** [comment]
@mMoliere That is fine, go ahead and add it to the schemas and I will add it to the form generator.

**Comment by mMoliere** [comment]
Great, thank you! 

I will keep this issue open to remind us both.

**Comment by wsalesky** [comment]
@mMoliere is there an update to the schema for this?

**Comment by mMoliere** [comment]
@wsalesky Not yet, probably next week.

**Comment by wsalesky** [comment]
@mMoliere What is the status of this? Is it in the schema? Is it still a feature you would like implemented?

**Comment by wsalesky** [comment]
@mMoliere are there examples of this in the schema? It should be simple to implement, but I like a test case.
