### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#493]
@wsalesky There is a bug that has the following effect: After opening an entry in manuscript or persons, only one subform can be opened. If another is selected the app does not respond. But it is possible to return to the main menu. The "Admin menu" is also not affected. I am confident that this bug is connected to a recent modification – once I reverted to the older branch the bug was gone.

**Comment by wsalesky** [comment]
@mMoliere Thanks, I will take a look. What is the most recent pull request that you noticed the issue on?

**Comment by mMoliere** [comment]
@wsalesky It was either #484 or #425.

**Comment by mMoliere** [comment]
@wsalesky Thank you, this works great!
