### ISSUE TITLE
Empty white boxes

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#496]
@wsalesky Where are we regarding the empty white boxes? If memory serves, we decided on manipulating the CSS after the designers were not able to help.
![Screenshot 2024-01-10 at 10-57-12 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/306f1353-8d78-4fb3-864f-7abbd2e72f4c)

**Comment by wsalesky** [comment]
@mMoliere remind me, is this only on firefox, or is it in chrome as well? I did think we fixed this, but maybe not.

**Comment by mMoliere** [comment]
@wsalesky Indeed, you have solved the problem for Chrome. Sorry for bothering you about this!

**Comment by wsalesky** [comment]
@mMoliere I can try to solve it for Firefox also, but lets put it on the back burner until I get the other bugs sorted out.
