### ISSUE TITLE
Error: Switching between manuscript records

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#504]
@wsalesky Our first team member working with manuForma on a regular basis has reported the following error:

> I had submitted (Yevr.-Arab. I 190 = 122.xml) and merged it in to the Github repository, then I went to 'Main Page' in ManuForma, entered '191' for the next MS, selected it and chose 'Load selected record', then the confirmation appeared (cf. screenshot) and yet the old Yevr-Arab. 190 is still loaded. Even after I clicked 'Ok' to remove the confirmation message (cf. second screenshot).
> I always have to repeat this process 2-3 times until the correct MS is loaded.

As I understand him, this occurs occasionally and he feels it is distracting him.

![grafik](https://github.com/majlis-erc/manuForma/assets/73166992/0acaa53f-a606-48e3-a822-d52b49322909)
![grafik(1)](https://github.com/majlis-erc/manuForma/assets/73166992/d8fb0667-0776-4d5f-906b-b0a9aa6e8ed3)

**Comment by wsalesky** [comment]
@mMoliere Have you had this problem? I have not been able to replicate it yet. Also, do you know what browser he is using?

**Comment by mMoliere** [comment]
No,a team member reported it. He is working in Firefox.

**Comment by mMoliere** [comment]
The error has not ocurred for one month. Let's assume it is not of concern (for the moment).
