### ISSUE TITLE
Bug: Look up

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#507]
@wsalesky The look up feature is causing a strange bug:

This file (MAJLIS-6.xml) has the name of an author, but we need to look up his ID:
![Screenshot 2024-01-23 at 16-14-28 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/a8e32a04-fb5c-437a-9abc-39addbf98156)

The search in look up turns up this result which is then selected and loaded:
![Screenshot 2024-01-23 at 16-14-52 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/628d3e56-cce2-4cae-9cdd-a298fffa262e)

The result is that the entire `author`-element vanishes from the record:
![Screenshot 2024-01-23 at 16-15-26 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/491974c4-0fe0-46b2-9924-b3c1d7096efa)

It gets even weirder. When I try to create a new `author`-element manuForma opens the persons look up feature! I then select "Add to record" …

![Screenshot 2024-01-23 at 16-15-49 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/1601e7cc-9d0c-4aee-8571-72882dd192ff)

… which creates a new blank `author`-element:
![Screenshot 2024-01-23 at 16-16-07 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/152b2174-0db9-40b2-88c0-2c0a6e764fd1)

But this is of no use. When I try to use the look up feature, the same thing happens: the element is deleted.

I have tested this bug both on Chrome and Firefox and with several files. It also when using look up with other fields (`bibl, title, place`).

**Comment by wsalesky** [comment]
@mMoliere Yikes! I will take a look. I have meetings today but hopefully I can get it sorted out by end of the day tomorrow.

**Comment by mMoliere** [comment]
@wsalesky Thank you!

**Comment by wsalesky** [comment]
@mMoliere I have the first part fixed. I'm not sure I understand the second part? 
'It gets even weirder. When I try to create a new author-element manuForma opens the persons look up feature!'
How are you creating the new author element? 

In the meantime, please try the update here: https://github.com/majlis-erc/manuForma/pull/513

**Comment by mMoliere** [comment]
@wsalesky I created the new Author element in the menu bar of the collapsible. This feature also works fine now. Thank you!
