### ISSUE TITLE
Conflict

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#51]
By merging the development branch into main, some changes I made two weeks have disappeared. What immediately caught my eye is that a new subform using `decoDesc` has vanished from manuForma.

Could you restore the changes that I made and reconcile them with your recent merge of the development version?

**Comment by wsalesky** [comment]
@mMoliere I will check my merge and see what happened.

**Comment by wsalesky** [comment]
Resolved.

**Comment by wsalesky** [comment]
@mMoliere Would you like me to rerun the MS forms? Or would you like to do it?
