### ISSUE TITLE
Title in heritage data collapsible only sometimes displayed

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#519]
@wsalesky We want the collapsibles in Heritage data to display the `title` inside the `bibl` element:
 
https://github.com/majlis-erc/manuForma/blob/1be36d6d5ad93282058ad4033715a3be9ac88694/forms/templates/full-mss-template.xml#L214

This works not as we expected:

- If you add a string to the `title` element after you have opened the record in manuForma, the `title` is displayed in the collapsible:

![Screenshot 2024-01-25 at 09-37-37 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/f6d89f02-d0cc-41ef-bb27-b41fbade88be)

- But, in many cases we import the content of the `title` element from our temporary database via XSLT. **And these `titles` are not displayed.** 

![Screenshot 2024-01-25 at 09-32-49 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/a4e23ea6-124d-452b-9f9f-dc8e5e3dd00d)

Example: 
 
https://github.com/majlis-erc/majlis-data/blob/4b30ecb10e55050974bf72a025f67ea3a76675f9/data/manuscripts/tei/1.xml#L292-L296

We import other `bibl` elements whose `title` elements from our temporary database are displayed without giving us any trouble:
![Screenshot 2024-01-25 at 09-43-13 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/775f1932-c9d9-4c0d-8eaa-039b449f2c19)

**Comment by wsalesky** [comment]
@mMoliere This is a setting in the configuration file. Compare these two lines: 

https://github.com/majlis-erc/manuForma/blob/main/forms/formGenerator/config-mss.xml#L539
Here the heading is hardcoded into the configuration file. 


https://github.com/majlis-erc/manuForma/blob/main/forms/formGenerator/config-mss.xml#L568
Here the heading is created using an xpath. 

I hope that helps.

**Comment by mMoliere** [comment]
@wsalesky I don't really get what you mean. Both are XPaths, the only difference that I can see is that the one not working has a child element.

**Comment by wsalesky** [comment]
@mMoliere You are right. I'm sorry, I think my local version of this file must be different. Sorry for the confusion. Try changing this line: 
https://github.com/majlis-erc/manuForma/blob/main/forms/formGenerator/config-mss.xml#L539

from: 
`                <group groupLabel="Quotation from and information about the heritage material." groupLabelConditionalElement="./*:bibl/title" groupLabelXPath="./*:bibl/title" groupNo="1" repeatable="yes">`

to:
                `<group groupLabel="Quotation from and information about the heritage material." groupLabelConditionalElement="./*:bibl/*:title" groupLabelXPath="./*:bibl/*:title" groupNo="1" repeatable="yes">`

The issue appears to be the missing namespace. I have not tested this, so let me know if that does not solve the issue.
