### ISSUE TITLE
Persons – idno not displayed

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#533]
@wsalesky In the subform "Linked Open Data" we want to display external identifiers. The trouble is that the field 'idno' only displays the two attributes, but not the text node.

Example file 4.xml, Line 144:

![Screenshot 2024-01-29 at 17-22-47 Edit Person TEI records](https://github.com/majlis-erc/manuForma/assets/73166992/ab1f017b-d203-4ce9-be70-ede5dd32b2e5)

**Comment by wsalesky** [comment]
@mMoliere Can you give me an example of what the idno element looks like on the backend? Just past a TEI snippit into the issue so I can make sure I know what is missing in the form. Thanks.

**Comment by wsalesky** [comment]
@mMoliere See this change to the config file (the 'global' rules were overriding the local):  https://github.com/majlis-erc/manuForma/pull/543

**Comment by mMoliere** [comment]
@wsalesky Thank you!
