### ISSUE TITLE
New Feature: Autogenerate file number

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#534]
@wsalesky On "Main Page / New record" we can create new XML files. So far, we assign file names by hand. In the future, we would like to automate this step:

manuforma should look into the folder scan which span of numbers is already assigned to records and then pick the next highest number. This number is assigned to the file name and to 

```
<idno type="URI">https://jalit.org/manuscript/</idno>
<idno type="URI">https://jalit.org/person/</idno>
<idno type="URI">https://jalit.org/work/</idno>
<idno type="URI">https://jalit.org/place/</idno>
<idno type="URI">https://jalit.org/relation/</idno>
```
All of this is happening in the background without any additional action from the users.

Do you think this is doable?

**Comment by mMoliere** [comment]
@wsalesky The project team has asked about this again.

**Comment by mMoliere** [comment]
@wsalesky Please make this feature your priority.

**Comment by wsalesky** [comment]
See updates here: https://github.com/majlis-erc/manuForma/pull/608
