### ISSUE TITLE
Person: ID search error

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#535]
@wsalesky When searching the person files by ID, there is an error:

![Bildschirmfoto 2024-01-29 um 17 34 51](https://github.com/majlis-erc/manuForma/assets/73166992/d5275f67-fbb1-4207-8269-5c977f888899)

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/manuForma/pull/539

**Comment by wsalesky** [comment]
@mMoliere has this been resolved?

**Comment by mMoliere** [comment]
Yes!
