### ISSUE TITLE
Manuscripts: Bibliography Search

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#536]
@wsalesky When searching for bibliography records that have been imported from our Zotero DB, the results have not the expected form. We would like to see the author's name and the title. However, manuForma only displays the title:

![Screenshot 2024-01-29 at 18-07-47 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/dd0399c8-5bf0-4086-86d3-679965b01c63)

In this example we would expect to see among the results:

"Skoss. A Study of the Uses of Letter "Yod" by David Ben Abraham Al-Fasi." [or something similar]

Instead we get "A Study of the Uses of Letter "Yod" by David Ben Abraham Al-Fasi."

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/manuForma/pull/540

**Comment by wsalesky** [comment]
@mMoliere Did this resolve the issue?

**Comment by mMoliere** [comment]
Yes, it works perfectly. Thank you!
