### ISSUE TITLE
Relations: Add lookup 

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#563]
@wsalesky We want to begin work on relations soon. For that to work some modifications need to be made to the lookup feature:

In our schema, the element <relation> contains attributes for the kind of relationship (@name) and the persons involved (@active, @passive, @mutual):
https://github.com/majlis-erc/manuForma/blob/80f59d1b3e3d071c52c6d1cf9f1d06d8d3e458f4/forms/templates/relations-template.xml#L3

For each of these attributes we want to be able add separate references to person records.

Another complication: the attribute @mutual allows 1+n references.

**Comment by wsalesky** [comment]
@mMoliere Are you asking for a lookup on each attribute?

**Comment by wsalesky** [comment]
@mMoliere Sounds good. I will see what I can do.

**Comment by wsalesky** [comment]
@mMoliere Just to be clear, this needs to do lookups across all data types? Persons, places and works?

**Comment by mMoliere** [comment]
@wsalesky Yes, all data types

**Comment by mMoliere** [comment]
@wsalesky Please make this feature your highest priority in your work for us.

**Comment by mMoliere** [comment]
@wsalesky Do you have any news?

**Comment by wsalesky** [comment]
@mMoliere This is a complicated addition, the forms are not really made for adding multiple values the way you would like to.  Unfortunatly I have not had time to experiment with alternative solutions. My summer schedule is very packed, I can bug fixes and small updates, but this will have to wait until the fall. Sorry for the bad news.

**Comment by mMoliere** [comment]
@wsalesky Ok, but please make this one a priority when you have more time after the summer.

**Comment by mMoliere** [comment]
@wsalesky Have you taken a look at this again?

**Comment by wsalesky** [comment]
Not until September. On Aug 21, 2024, at 7:43 AM, mMoliere ***@***.***> wrote:﻿
@wsalesky Have you taken a look at this again?

**Comment by mMoliere** [comment]
@wsalesky OK, I can work with that. Thanks

**Comment by wsalesky** [comment]
@mMoliere quick question on this, is @mutual the only attribute that will need to accept multiple values? or should it be enabled for @passive and @active as well?

**Comment by wsalesky** [comment]
@mMoliere This feature is ready for testing. Please make sure to merge this: https://github.com/majlis-erc/srophe/pull/186

As the lookups will not work without it. Let me know how it goes.

**Comment by mMoliere** [comment]
Hi @wsalesky, I ran the updated XSLT on the relations forms. The new fields are being displayed as expected. I can open the lookup. But when I try to search for other records, no results are being displayed. Am I overlooking something? Is there something that I should adjust in the config?

This is as far as I get:

![Screenshot 2024-09-30 at 08-57-15 Edit Relation TEI Records](https://github.com/user-attachments/assets/896d7977-4692-4ddc-bd44-763763d107dd)

**Comment by wsalesky** [comment]
@mMoliere You will need to merge this change as well to get the lookups working correctly: 
https://github.com/majlis-erc/srophe/pull/186

**Comment by mMoliere** [comment]
@wsalesky Ah, I missed that …

**Comment by mMoliere** [comment]
@wsalesky This works already really well!

We need two tweaks to make it perfect:

1) When records are linked the human-readable name is displayed alongside the identifier:
![Screenshot 2024-10-04 at 16-46-16 Edit Relation TEI Records](https://github.com/user-attachments/assets/c449c791-8cda-4e73-8a3c-36e5e952f131)


After submitting the record and loading it again, only the identifier is displayed:
![Screenshot 2024-10-04 at 16-46-28 Edit Relation TEI Records](https://github.com/user-attachments/assets/0e723188-1b22-49cf-9638-912feea892b3)

 We would like the human-readable name to be there as well.

2) The lookup window needs to be decluttered. Remove all [citation] – they are not relevant to relations.

If possible we would like the ability to filter the results by record type: person, manuscript, work, place.

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/187
and: https://github.com/majlis-erc/manuForma/pull/658

**Comment by mMoliere** [comment]
@wsalesky It works beautifully!
