### ISSUE TITLE
Manuscripts: Superfluous lookups

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#569]
@wsalesky In the manuscript module there are superfluous lookups (and "Create new title") for some `bibl` elements. Whenever the `bibl` element contains a `title` element, there is also a lookup. Because `bibl` elements have their own lookups, this creates confusion among the users which lookup they should use.

As a rule: the only instance where the `title` element requires the lookup (and "Create new title")  is inside `msItem`, that is in the _Content description_ subform.

Below is an example:
![Screenshot 2024-04-10 at 10-43-21 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/876b848b-ae54-470e-b93d-12c2506e79df)

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/manuForma/pull/597
