### ISSUE TITLE
New Feature: Display Custom Field Names in Dropdowns

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#58]
@wsalesky So far when we want to a new child element we select its TEI name from the dropdown. We would like the custom names to appear there instead.

**Comment by wsalesky** [comment]
Fixed by: https://github.com/majlis-erc/manuForma/pull/60/commits/ffc4d0573279dcd51e599785a0094fea2da2f7c0

This pull request updates the XSLT and reruns the MS forms only. To update the other forms they will need to be run through the form generator.
