### ISSUE TITLE
Manuscripts: Lookup error

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#582]
@wsalesky When trying to use the lookup in Manuscript, subform Codicological definition / Manuscript joins there is an error message that no root element has been found at: `https://manuforma-staging.jalit.org/exist/apps/manuForma/form.xq?form=forms/msSimple/index.xhtml#/ line 1, row 139:<?xml-stylesheet type="text/xsl" href="/exist/rest/db/apps/xsltforms/xsltforms.xsl"?><?css-conversion no?><?xsltforms-options debug="no"?>`

I don't know what to do about it. Please take a look

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/manuForma/pull/583
