### ISSUE TITLE
Lookup for more than one record type

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#587]
@wsalesky For the Bibliography in Persons we want to be able to reference records from the **manuscripts**, **bibl**, and the **works** collections. I'm unsure how to make this request to the API or if this is even possible. (I have played with different formulations for the API request but none worked out.)

**Comment by wsalesky** [comment]
Done. Multiple collections can be specified in the collection parameter, separated by a comma. See config documentation for how to.  https://github.com/majlis-erc/manuForma/blob/main/forms/formGenerator/config-documentation.xml#L76

Example lookup, searching multiple collections: 

```
<lookup api="/exist/apps/majlis/api/search/biblWorksCitation?format=xml&amp;collection=manuscripts,bibl&amp;q=" 
            elementName="bibl" 
            formName="bibl" 
            lookupLabel="Look up bibliographic record"/>
```
