### ISSUE TITLE
Increase time before logout

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#588]
@wsalesky Our users report that they get logged out of ManuForma after 2 to 5 minutes of inactivity. As a resulte they have to login again after a few minutes. Sometimes this means that their previous work is lost. As a result, they submit their changes every few minutes, merge their changes and reopen the record in manuForma. This makes concentrating on their work very difficult. Please try to extend that time.

**Comment by wsalesky** [comment]
See here: https://github.com/majlis-erc/manuForma/pull/589

Please merge and test.

**Comment by mMoliere** [comment]
@wsalesky I'm not sure to which of your recent updates this is related. But when I open one the forms, I get the following message: 


> XSLTForms Exception
> --------------------------
> 
> Error dispatching event 'xforms-model-construct' :
> 
> xforms-link-exception

**Comment by wsalesky** [comment]
@mMoliere I will take a look.

**Comment by wsalesky** [comment]
See fix here: https://github.com/majlis-erc/manuForma/pull/593

**Comment by mMoliere** [comment]
Thanks. This error is now gone.

**Comment by mMoliere** [comment]
@wsalesky So far the improvements work great!

**Comment by wsalesky** [comment]
Great, keep me posted. This should keep users logged in for 7 days.
