### ISSUE TITLE
Second Mouse Over 

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#59]
@wsalesky The project leadership wants the UI to be less distracting to users and remove the TEI field names. Some people, me included, need the original TEI names for debugging etc. Our compromise is as follows: We want a second mouse over that takes the contents of `<gloss type="tei">`. The symbol will be the TEI logo.

**Comment by wsalesky** [comment]
@mMoliere Can you send me a mockup?

**Comment by mMoliere** [comment]
@wsalesky we have a conference this week. Maybe I will get around to prepare one.

**Comment by mMoliere** [comment]
@wsalesky Sorry for the delay. This is how we imagine this button to look like:
[Secondary Mouseover.pdf](https://github.com/majlis-erc/manuForma/files/10549942/Secondary.Mouseover.pdf)

**Comment by wsalesky** [comment]
@mMoliere should be an easy addition, is this data in the schema already?

**Comment by mMoliere** [comment]
@wsalesky I have created the data in the schema and opened a pull request.

**Comment by wsalesky** [comment]
@mMoliere Sorry, can you send me a link to the pull request, or has it already been merged in?

**Comment by mMoliere** [comment]
@wsalesky I sent you a request to review

**Comment by wsalesky** [comment]
Fixed by this #63 pull request. Let me know what you think. Turns out we do not need a gloss if all you want is the TEI element name.

**Comment by mMoliere** [comment]
@wsalesky The second mouse over works – but the TEI-symbol is not displayed. Instead, we only see the "broken image" symbol.

**Comment by mMoliere** [comment]
The image is displayed, but now it is too large and the labels are displayed behind the image: 
![Bildschirmfoto 2023-03-06 um 18 54 22](https://user-images.githubusercontent.com/73166992/223191853-edafd7c1-5a62-43e2-a7ed-bebfeed864fc.png)

**Comment by wsalesky** [comment]
I updated the css, can you try again? A hard refresh may be necessary.
