### ISSUE TITLE
No Revision message possible

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#612]
@wsalesky When submitting a Works record to GitHub. The window where one is supposed to enter one's change message does not allow entering any text.

![Screenshot 2024-05-21 at 11-24-09 Edit Works TEI records](https://github.com/majlis-erc/manuForma/assets/73166992/d4518b57-2a11-4314-b17e-954c29494b36)

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/manuForma/pull/614

There should be a change element in the xml templates.
