### ISSUE TITLE
MSS Error Message

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#626]
@wsalesky When submitting changes for a manuscript entry, I get the error message: "Unable to submit your additions at this time, you may download your changes and email them to us."   

Can you take a look?

**Comment by wsalesky** [comment]
@mMoliere I will take a look. I was able to submit a record, but the forwarding to the pull request did not work. So there is a bug somewhere.

**Comment by mMoliere** [comment]
@wsalesky Yes, please sort this out.

**Comment by mMoliere** [comment]
@wsalesky Update, it seems to be a wider problem: I'm experiencing the same problem with manuscripts. There seems to be a webhook error. But the pane for "Recent deliveries" is not displaying anything. The git-sync.xql file on the server looks normal.

**Comment by mMoliere** [comment]
@wsalesky The webhook appears to be working now. But I still can't submit even after clearing my cache several times.

**Comment by wsalesky** [comment]
@mMoliere can you clarify what you mean by can't submit? Do you get an error? Can you try opening your chrome javascript debugger, click on the 'network' tab and taking a screenshot of the response you are getting?  What browser are you using?

**Comment by wsalesky** [comment]
@mMoliere Please try again, I think the github token in the git-commit.xql file got deleted on the latest update. I have manually added it back in. Just do a hard refresh on the server and give it another try. Thanks

**Comment by mMoliere** [comment]
@wsalesky When I try to submit my changes from manuForma I receive the message "Unable to submit your additions at this time, you may download your changes and email them to us." What do you mean by "hard refresh on the server"?

**Comment by wsalesky** [comment]
@mMoliere What browser are you using? See screen shot for how to do a hard refresh in chrome. (You will need to open the javascript debugging tools to get the hard refresh)
<img width="1001" alt="Screenshot 2024-06-17 at 10 38 45 AM" src="https://github.com/majlis-erc/manuForma/assets/1168206/a3c6b371-1949-41d1-8adc-5d9fb04aeb6a">

**Comment by mMoliere** [comment]
@wsalesky I have tried hard refresh both on Chrome and Firefox. The result is always the same error message when I submit changes.

**Comment by wsalesky** [comment]
@mMoliere is it different if you login as 'admin' ?

**Comment by wsalesky** [comment]
@mMoliere how odd. I have not been able to reproduce it. I will keep trying.

**Comment by mMoliere** [comment]
@wsalesky Thank you!

**Comment by mMoliere** [comment]
@wsalesky Have you had any ideas what is happening? We can't continue with our work until this error is resolved.

**Comment by wsalesky** [comment]
@mMoliere I can not reproduce this error. I have successfully saved multiple records. The latest here: https://github.com/majlis-erc/majlis-data/pull/710

Is anyone else using the form? If so are they having the same issue? Is this all from one computer? If yes, can you try restarting it? It may be some sort of caching issue.

**Comment by mMoliere** [comment]
@wsalesky Your suggestion to restart my computer was good, but unfortunately it did not work. I have tried it on two other computers with the same negative results.

**Comment by wsalesky** [comment]
@mMoliere what username are you using?

**Comment by mMoliere** [comment]
@wsalesky mmoliere

**Comment by mMoliere** [comment]
@wsalesky It is the same if I use the admin account.

**Comment by wsalesky** [comment]
@mMoliere I'm going to move the discussion to email.
