### ISSUE TITLE
Persons: Submit bug

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#634]
@wsalesky There seems to be another submit error. This time it is in Persons. When I try to submit my changes to Github the usual error message is displayed.

Following our last dialog on this matter, I have availed myself of the diagnostic tool and recorded the response from the server:

```
<?xml version="1.0" ?><exception><path>/db/apps/manuForma/services/submit.xql</path><message>err:FODC0006 String passed to fn:parse-xml is not a well-formed XML document.: Document is not valid.
Fatal (1,301) : The reference to entity &quot;s.f.s2_parent&quot; must end with the ';' delimiter.
Validated in -1 millisec.
 [at line 60, column 28, source: /db/apps/manuForma/services/submit.xql]
In function:
	local:transform(node()*) [278:5:/db/apps/manuForma/services/submit.xql]
	local:passthru(node()*) [163:13:/db/apps/manuForma/services/submit.xql]
	local:transform(node()*) [131:32:/db/apps/manuForma/services/submit.xql]
	local:transform(node()*) [173:32:/db/apps/manuForma/services/submit.xql]
	local:transform(node()*) [278:5:/db/apps/manuForma/services/submit.xql]
	local:passthru(node()*) [266:31:/db/apps/manuForma/services/submit.xql]
	local:transform(node()*) [278:5:/db/apps/manuForma/services/submit.xql]
	local:passthru(node()*) [266:31:/db/apps/manuForma/services/submit.xql]
	local:transform(node()*) [278:5:/db/apps/manuForma/services/submit.xql]
	local:passthru(node()*) [266:31:/db/apps/manuForma/services/submit.xql]
	local:transform(node()*) [63:53:/db/apps/manuForma/services/submit.xql]
	local:transform(node()*) [311:28:/db/apps/manuForma/services/submit.xql]</message></exception>
```

**Comment by wsalesky** [comment]
@mMoliere I will take a look. Can you tell me what record? Also, did you add this: &quot;s.f.s2_parent&quot; if so, to what element and what was the format?  Was it &quot;s.f.s2_parent&quot; or "s.f.s2_parent" or something else. Thanks!

**Comment by mMoliere** [comment]
@wsalesky The record was 25.xml. 

No, I did not add "s.f.s2_parent". That is not something that we would add to our files.

**Comment by wsalesky** [comment]
@mMoliere I found it, it is in a bibl element, in a link. The problem is the url is not escaped. I will see what I can do.

**Comment by mMoliere** [comment]
@wsalesky Did you solve it?

**Comment by wsalesky** [comment]
@mMoliere please try this fix.
https://github.com/majlis-erc/manuForma/pull/635

**Comment by mMoliere** [comment]
@wsalesky Thank you! That works great!
