### ISSUE TITLE
MSS: Text editor – unexpected behavior

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#636]
@wsalesky The new text editor capabilities work great. Thank you again for that!

There is just one problem: manuForma can't distinguish between linebreaks that are intended by the users and indentations in the code that are generated by Oxygen XML etc.

Here is an example where manuForma added `<lb>` elements that shouldn't be there:

![Screenshot 2024-07-02 at 18-15-29 Updates from online corrections  data_manuscripts_tei_1441 xml by mMoliere · Pull Request #742 · majlis-erc_majlis-data](https://github.com/majlis-erc/manuForma/assets/73166992/bb1f5f48-1260-47bd-a153-12f8dcd576df)

Is this something that can be fixed by modifying the code? From the top of my head, I would think that `<lb>` elements should not be added when there are 3 or more spaces after the linebreak. Is that feasible?

**Comment by wsalesky** [comment]
@mMoliere please try this. 
https://github.com/majlis-erc/manuForma/pull/637
