### ISSUE TITLE
Manuscripts: manuForma creates unwanted elements

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#638]
@wsalesky manuForma creates `editor` elements in `titleStmt` without the user's intention. For example:

https://github.com/majlis-erc/majlis-data/blob/f2f64eaf0bba831c1ee98f421b4429bca2296124/data/manuscripts/tei/514.xml#L29-L35

Can you try to fix this?

**Comment by mMoliere** [comment]
@wsalesky Have you had a chance to look into this?

**Comment by wsalesky** [comment]
Try this: https://github.com/majlis-erc/manuForma/pull/702

**Comment by wsalesky** [comment]
@mMoliere has this been resolved?

**Comment by mMoliere** [comment]
@wsalesky I have tested the update. It does not yet seem to work:

![Screenshot 2024-12-10 at 09-56-10 Updates from online corrections  data_manuscripts_tei_1554 xml by mMoliere · Pull Request #1168 · majlis-erc_majlis-data](https://github.com/user-attachments/assets/657d283b-ad9b-4dc9-b5b7-a176b9074367)

**Comment by wsalesky** [comment]
@mMoliere How are you updating these? Do you use the 'continue working with an existing record' option? I'm just trying to narrow down where the elements are being introduced. (Not in the submit function, so maybe in the load function)

**Comment by wsalesky** [comment]
@mMoliere do users add their own editor information? This is supposed to add an editor statement and insert the current users info, however, this would lead to a lot of duplication, and appears to not actually correctly grab the logged in users information. I can turn off the code that inserts this element, and you can make sure the editors add an editor element for themselves. That would probably be the best way to control the proliferation of unneeded editor elements. What do you think?

**Comment by mMoliere** [comment]
@wsalesky Yes, I'm using use the 'continue working with an existing record' option. I search for the ID. I make changes. I submit.

Users don't add their own editor information. They don't touch that part of the template. So I think we should do as you suggest.

**Comment by mMoliere** [comment]
@wsalesky Any progress here?

**Comment by wsalesky** [comment]
Give this a try please: https://github.com/majlis-erc/manuForma/pull/742
