### ISSUE TITLE
Manuscripts: text fields create arrays of p elements

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#639]
@wsalesky We are big fans of the new text fields. But they seem to add new empty `p` elements every time the file is submitted to GitHub. For example this file has been worked a lot in the past weeks and in the text fields groups of empty `p` elements have accumulated:

https://github.com/majlis-erc/majlis-data/blob/f2f64eaf0bba831c1ee98f421b4429bca2296124/data/manuscripts/tei/514.xml#L159-L161

https://github.com/majlis-erc/majlis-data/blob/f2f64eaf0bba831c1ee98f421b4429bca2296124/data/manuscripts/tei/514.xml#L255C37-L266C70

**Comment by wsalesky** [comment]
Try this fix please: https://github.com/majlis-erc/manuForma/pull/703

**Comment by mMoliere** [comment]
@wsalesky I have tested the update. Strings in some `p` element (in the `license` and `sourceDesc` elements) are being deleted.

![Screenshot 2024-12-10 at 09-52-33 Updates from online corrections  data_manuscripts_tei_1554 xml by mMoliere · Pull Request #1168 · majlis-erc_majlis-data](https://github.com/user-attachments/assets/6427f718-c03d-4ed6-9e06-29156092a553)


Additional p elements are still being created:

![Screenshot 2024-12-10 at 10-03-43 Updates from online corrections  data_manuscripts_tei_1554 xml by mMoliere · Pull Request #1169 · majlis-erc_majlis-data](https://github.com/user-attachments/assets/e600a32b-d59f-48e4-ae7b-da2c21f2ab23)

**Comment by wsalesky** [comment]
@mMoliere I am going to roll back this change. And then do some debugging locally. Sorry about that

**Comment by mMoliere** [comment]
@wsalesky The additional `p` elements inside `note` and `quote` elements are indeed gone!

But the contents of the `license` and `source` elements is still deleted. Also, when submitting a new version spaces are added at the beginning of a `p` element.

![Screenshot 2024-12-10 at 16-44-22 Updates from online corrections  data_manuscripts_tei_1556 xml by mMoliere · Pull Request #1172 · majlis-erc_majlis-data](https://github.com/user-attachments/assets/c333926f-e6eb-48e9-a128-a42b7b073c47)

**Comment by wsalesky** [comment]
@mMoliere Okay, well, we are getting closer, I think the missing content is a different issue. So I'm going to split it out. I will investigate the new space issue.

**Comment by mMoliere** [comment]
@wsalesky Sounds good!
