### ISSUE TITLE
Look ups: Still struggling …

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#675]
@wsalesky I'm still having trouble to get the lookups to run smoothly in the manuscript part of the app. However, other lookups work just fine. 

# Here is a detailed list of bugs with links to the code:

## Content description [(Code)](https://github.com/majlis-erc/manuForma/blob/433481843d628a9ce54761c120c6f7b7dbe950d8/forms/formGenerator/config-mss.xml#L299-L324)

- Canonical title (`author`): no search results
- Canonical author name (`title`): display error, see below:

![Screenshot 2024-10-30 at 17-53-26 Edit MS TEI Records](https://github.com/user-attachments/assets/3620a280-6152-415b-ab18-e3dd1d0f645a)

## Heritage data [(Code)](https://github.com/majlis-erc/manuForma/blob/433481843d628a9ce54761c120c6f7b7dbe950d8/forms/formGenerator/config-mss.xml#L641-L664)

- Bibliographic reference (`bibl`): look up searches in `manuscript collection` instead of `bibl collection`
- Title of publication (`title`): look up button and create new button are not suppressed

## Bibliography [(Code)](https://github.com/majlis-erc/manuForma/blob/433481843d628a9ce54761c120c6f7b7dbe950d8/forms/formGenerator/config-mss.xml#L694-L711)

- Bibliographic reference (`bibl`): copies the string value of the reference text twice into `title`
- Title of publication (`title`): look up button and create new button are not suppressed

# The following lookups work as expected:

## Physical description: script/hand description [(Code)](https://github.com/majlis-erc/manuForma/blob/433481843d628a9ce54761c120c6f7b7dbe950d8/forms/formGenerator/config-mss.xml#L495-L520)

- Person 
- Place 

## Incodicated documents [(Code)](https://github.com/majlis-erc/manuForma/blob/433481843d628a9ce54761c120c6f7b7dbe950d8/forms/formGenerator/config-mss.xml#L521-L598)

- Person 
- Place 

## Heritage data [(Code)](https://github.com/majlis-erc/manuForma/blob/433481843d628a9ce54761c120c6f7b7dbe950d8/forms/formGenerator/config-mss.xml#L641-L664)

- Person 

## Manuscript history [(Code)](https://github.com/majlis-erc/manuForma/blob/433481843d628a9ce54761c120c6f7b7dbe950d8/forms/formGenerator/config-mss.xml#L665-L693)

- Place 
- Person

**Comment by wsalesky** [comment]
@mMoliere I am working on this today. I'm having some trouble getting the lookups to be hidden when needed properly.

**Comment by mMoliere** [comment]
@wsalesky We're getting somewhere, but there are still some bugs. I have created a new test document (manuscripts/1554.xml) for you to examine.


## Content description 

- Canonical title (`author`): still no search results ✖︎
- Canonical author name (`title`): look up search results are given twice. The 'double' result is slightly indented. When adding the double result to the record a second `title` element is created – nested inside the original `title` element. ✖︎

![Screenshot 2024-11-12 at 12-34-02 Edit MS TEI Records](https://github.com/user-attachments/assets/e1809bc4-8d77-45f8-a708-89eda4a0a01e)

![Screenshot 2024-11-12 at 12-35-04 Edit MS TEI Records](https://github.com/user-attachments/assets/98322fc9-bc66-4645-8236-50fe4ed3bd1d)


## Heritage data 

- Bibliographic reference (`bibl`): look up searches in `bibl collection` ✔︎
- Title of publication (`title`): look up button is suppressed ✔︎

## Bibliography 

- Bibliographic reference (`bibl`): look up no search results ✖︎
- Title of publication (`title`): look up button is suppressed ✔︎

# The look ups that previously worked now suffer from the same bug as `title`. 

## Physical description: script/hand description 

- Person when adding to the record, a second `persName` element is created nested into the original `persName` element ✖︎
- Place when adding to the record, a second `placeName` element is created nested into the original `placeName` element ✖︎

Also, this subform triggered the first in series of error messages: 

`WARNING: Duplicate ids: xsltforms-mainform-output-2_2_2_4_2_4_4_4_ xsltforms-mainform-output-4_2_2_4_2_4_4_4_ `

## Incodicated documents 

- Person when adding to the record, a second `persName` element is created nested into the original `persName` element ✖︎
- Place when adding to the record, a second `placeName` element is created nested into the original `placeName` element ✖︎

## Heritage data 

- Person when adding to the record, a second `persName` element is created nested into the original `persName` element ✖︎

## Manuscript history 

- Person when adding to the record, a second `persName` element is created nested into the original `persName` element ✖︎
- Place when adding to the record, a second `placeName` element is created nested into the original `placeName` element ✖︎

**Comment by wsalesky** [comment]
@mMoliere  Try this one: https://github.com/majlis-erc/manuForma/pull/683

**Comment by wsalesky** [comment]
See: https://github.com/majlis-erc/srophe/pull/223

**Comment by wsalesky** [comment]
@mMoliere has this been resolved?
