### ISSUE TITLE
Persons: Error message

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#739]
@wsalesky I'm trying to filter out persNames with the type-attribute value "alternate".

```
<group groupLabel="Personal name." groupNo="1" repeatable="yes">
                    <element xpath="tei:persName[not(contains(@type, 'alternate'))]"/>
                </group>
```

Something curious happens. I receive the following error message:

```
XSLTForms Exception
--------------------------

Error parsing the following XPath expression :

instance('i-persNames-elementTemplate')/*[local-name() = 'persName[not(contains(@type, 'alternate'))]']

Unknown operator at 'alternate'))]']' in 'local-name() = 'persName[not(contains(@type, 'alternate'))]']' in 'instance('i-persNames-elementTemplate')/*[local-name() = 'persName[not(contains(@type, 'alternate'))]']'
```

But despite this message, I get the desired output in manuForma.

Is there a way to adjust what triggers an error message? Or is there a good reason for the error message and I should really not do what I'm doing?

![Screenshot 2024-12-18 at 09-40-31 Edit Person TEI records](https://github.com/user-attachments/assets/51f9d82c-6b83-4550-a738-e1d1edfe225d)

**Comment by wsalesky** [comment]
Please try this: https://github.com/majlis-erc/manuForma/pull/740
It will require an rebuild.
