### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#77]
@wsalesky our server admin is asking what the number of the most recent version of our images for manuForma, the data-app and srophé is. He needs to make changes and redeploy the apps.

**Comment by wsalesky** [comment]
Current version is 0.01. But this has old data and should probably be updated. In fact I think @nathangibson has a process that we should investigate which builds a new docker image when data on GitHub is updated. (Is that correct @nathangibson ?)

**Comment by mMoliere** [comment]
solved
