### ISSUE TITLE
Sections Repeat

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#83]
The plus and X buttons used to add the templates for sections should not be able to create secondary sections. This can can lead to invalid TEI.

Here is an example: 
![Bildschirmfoto 2023-03-07 um 15 43 10](https://user-images.githubusercontent.com/73166992/223456956-c1af4879-416c-4a23-bd87-e7cd9b25036b.png)

**Comment by wsalesky** [comment]
@mMoliere Still waiting on this, there are a lot of areas where we could limit how many elements can be added, or if there needs to be at least one, but I need that info in the schema somewhere to make this work.

**Comment by mMoliere** [comment]
@wsalesky Would it make things easy when I said that we don't need the subforms repeatable anymore? (We changed our mind about msPart. These things will be expressed another way.)

**Comment by wsalesky** [comment]
@mMoliere  So everything in the right hand menu (the subforms) will require 1 and only 1 occurrence? If so, yes, that  does make things easier on the top level. I'm still trying to work out a solution for internal controls, such as the summary element. But we will take it one step at a time.

**Comment by wsalesky** [comment]
@mMoliere Please see the latest version of the XSLT (1.06 Beta)

**Comment by mMoliere** [comment]
@wsalesky Something isn't right after this update:

When I try to open ManuForma, I get the following message:

```
XML processing error: No root element found
Address: https://manuforma-staging.jalit.org/exist/apps/manuForma/form.xq?form=forms/msSimple/index.xhtml
Line #1, column 139:
<?xml-stylesheet type="text/xsl" href="/exist/rest/db/apps/xsltforms/xsltforms.xsl"?><?css-conversion no?><?xsltforms-options debug="no"?>
------------------------------------------------------------------------------------------------------------------------------------------^
```

**Comment by wsalesky** [comment]
@mMoliere I can not reproduce this locally. I suggest you delete the msSimple directory and rebuild, this error might be caused by a bad merge, or a bad upload via webhooks.

**Comment by mMoliere** [comment]
@wsalesky Understood. To be clear: I delete the msSimple folder on the server or on my local branch before I rebuild it from the config and the XSLT?

**Comment by wsalesky** [comment]
@mMoliere to be safe I would delete it in both places. Let me know how it goes.

**Comment by mMoliere** [comment]
@wsalesky The webhook was acting up again:
As it turns out, the git-sync.xql on the server was gone for manuForma. (Also the entire msSimple had been removed fro the server!) For majlis-data it had reverted to the empty state. I filled them again with our credentials and gave them elevated rights. They seem to be working again.

Could these files have been deleted during a recent push to the server? How can we avoid this behavior in the future?

The msSimple folder is again on the server. However, now it gives the following error message:

```
XSLTForms Exception
--------------------------

Error dispatching event 'xforms-model-construct' :

xforms-link-exception
```

Is this something we need to work out? Or do you recommend deleting the folder again?

**Comment by wsalesky** [comment]
Is it possible your docker container was restarted? If it is not set up
with persistent storage then when the container goes down and then
restarts, it will reset. The webhooks would not have removed any of those
files.

In terms of your xforms issue, please make sure all the necessary files are
loaded, in particular make sure the templates and schema directories
present on the server, and up to date, this error occurs when the XForms
model is pointing to some file it can not find.

-Winona

**Comment by mMoliere** [comment]
It is a larger problem that affects manny of the universtiy servers in Munich. We have to wait this one out.

**Comment by mMoliere** [comment]
The server problem has not been resolved. In the meantime, I am working with a local eXist-DB install. When openeing mssSimple, it is currently displaying the error message: "Error loading the stylesheet: Parsing of an XSLT stylesheet failed." Do you get this on your installation? What XSLT can this refer to? My understanding is that XSLT is only used when compiling the XHTML files, right?

**Comment by wsalesky** [comment]
@mMoliere It sounds like you do not have the XSLTForms library installed. You can install it via the eXist-db dashboard.

**Comment by mMoliere** [comment]
@wsalesky That did it. It's a bit weird, on the original server the dependencies are be installed with manuForma.

The display of repeated collapsibles works. There are some unexpected behaviors when I try to reorder them using the up and down buttons:

DOWN: Another collapsible is created

![Bildschirmfoto 2023-03-28 um 08 14 50](https://user-images.githubusercontent.com/73166992/228146396-ce8c2f01-2732-4367-8fb0-dfbd7b9009f1.png)

![Bildschirmfoto 2023-03-28 um 08 18 02](https://user-images.githubusercontent.com/73166992/228146428-ca32fbe0-fe38-4fe2-8a18-54cd1c80abc9.png)


UP: All collapsibles are deleted.

![Bildschirmfoto 2023-03-28 um 08 15 34](https://user-images.githubusercontent.com/73166992/228146479-a707c397-8e1a-412c-b109-bf55e53fc9f8.png)

![Bildschirmfoto 2023-03-28 um 08 22 40](https://user-images.githubusercontent.com/73166992/228146645-7af10b22-2a5c-4689-9ced-b2bd907b327c.png)

**Comment by wsalesky** [comment]
@mMoliere I will take a look.
