### ISSUE TITLE
Economize buttons

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#85]
@wsalesky Is it possible to economize the number of buttons being displayed? Now, the buttons for adding attributes and elements are displayed all the time. However, this can be confusing to users when all attributes and elements are already there. Can you think of a way to hide the buttons when no more attributes and elements can be added?

Similarly, the up and down buttons should only be displayed, if the element can indeed be moved up or down.

Example: 
![Bildschirmfoto 2023-03-09 um 12 56 57](https://user-images.githubusercontent.com/73166992/224017170-198024e0-66fb-42b0-8d10-24f2da54b5ce.jpg)

**Comment by wsalesky** [comment]
@mMoliere I'm still working on this one, it is quite tricky, but I hope to have a fix soon.

**Comment by mMoliere** [comment]
@wsalesky I believe we talked about in similiar issue (I can't find it now) on the need to add constraints in the schema. As a test case, I have added `<sequence>` and `@minOccurs` and `@maxOccurs` in the msItem schema. Tell me if this is sufficient.

**Comment by wsalesky** [comment]
@mMoliere yes, that should be good. I will try to get something working next week. I'm trying to get through the remaining bugs as soon as I can. Some are proving trickier than expected, but I hope all are achievable.

**Comment by mMoliere** [comment]
Thank you!

**Comment by wsalesky** [comment]
@mMoliere It is not possible to hide the buttons when the correct number of elements have been added, the software simply does not support the necessary XPath needed to make it happen. However we do have warnings now if users add more elements then allowed by the schema.
