### ISSUE TITLE
Feature Request: Undo-Button

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#94]
I don't know if this is feasible: Our team is used to have undo-capabilities in their other programs. Is it at all possibe? If so, how difficult would it be to implement?

**Comment by wsalesky** [comment]
@mMoliere Undo for retrieving deleted text? Or retrieving deleted elements? The first is easy, although users can just use the control z function in the browser. It is unclear to me if the second is possible, but I could look into it.

**Comment by mMoliere** [comment]
@wsalesky Yes, retrieving deleted text works fine. But my colleagues also have retrieving deleted elements in mind.

**Comment by wsalesky** [comment]
@mMoliere This might be possible, but I do not have the development time available until next fall, so if you want to keep as a possible future development that would be fine.

**Comment by mMoliere** [comment]
@wsalesky That is fine. I don't consider this an essential feature. Let's close this issue for now.
