### ISSUE TITLE
Improve Mouse Over

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#96]
It feels the mouse over are is sometimes very hard to hit. Although the cursor is directly on the buttons you sometimes only get a response when you hit a very smal fraction of the icon. Is it possible to enlarge the area that triggers the message?

**Comment by mMoliere** [comment]
@wsalesky Most of us are using Firefox

**Comment by wsalesky** [comment]
@mMoliere Great, I will see what I can do.
