### ISSUE TITLE
Reproductions

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#97]
For `@source` we would like a dropdown list of the options stored in the schema.

**Comment by wsalesky** [comment]
@mMoliere Fixed. There was no reference to the graphic element as a child of the facsimile element in the schema. I added it to the schema and it now displays appropriately. See: https://github.com/majlis-erc/manuForma/blob/main/forms/schemas/mss-reproductions.xml#L112

**Comment by mMoliere** [comment]
@wsalesky Thank you for fixing this oversight!
