### ISSUE TITLE
Renaming attributes

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#98]
We have a request to rename an attribute (`msitem/@class`) into something that is more meaningful to the editors: "genre".

**Comment by wsalesky** [comment]
@mMoliere Where is this in the form and the schema?

**Comment by mMoliere** [comment]
@wsalesky 

schema: https://github.com/majlis-erc/manuForma/blob/43a17fa39a0cf221795698b923ae4297c2d185c1/forms/schemas/mss-msitem.xml#L307

Form: https://github.com/majlis-erc/manuForma/blob/43a17fa39a0cf221795698b923ae4297c2d185c1/forms/templates/full-mss-template.xml#L82

**Comment by mMoliere** [comment]
@wsalesky Ronny requests several more attributes to be renamed in the display.

**Comment by wsalesky** [comment]
@mMoliere can you add a label to the attDef? I think with the elements labels we add/change the gloss, is that an option for attributes? We will need something in the schema to rename them.

**Comment by mMoliere** [comment]
@wsalesky As a test, I have added gloss elements to one element in reproductions.
This gloss is a label for the name of the attribute: https://github.com/majlis-erc/manuForma/blob/5733cd15f0db5047c74cb96effd8a2a2e67fc168/forms/schemas/mss-reproductions.xml#L139

And these two are labels for the attribute's value:  https://github.com/majlis-erc/manuForma/blob/5733cd15f0db5047c74cb96effd8a2a2e67fc168/forms/schemas/mss-reproductions.xml#L142

https://github.com/majlis-erc/manuForma/blob/5733cd15f0db5047c74cb96effd8a2a2e67fc168/forms/schemas/mss-reproductions.xml#L145

**Comment by wsalesky** [comment]
This should be fixed with v 1.09. Reopen if you find any issues.

**Comment by mMoliere** [comment]
@wsalesky We would like to extend this feature. We want to rename the attribute values themselves for display in manuForma. They are stored as `gloss` inside `valItem`.

**Comment by wsalesky** [comment]
@mMoliere can you link to the place in the schema, so it is easier for me to test?

**Comment by mMoliere** [comment]
@wsalesky https://github.com/majlis-erc/manuForma/blob/03bbd32e23cabd31650a68b08f546bfa5bc71f84/forms/schemas/mss-msitem.xml#L278C69-L278C74

**Comment by mMoliere** [comment]
@wsalesky That works really well! Thank you!

**Comment by mMoliere** [comment]
@wsalesky This improvement is also gone from the redesigned version. 
![Screenshot 2023-07-17 at 22 25 53](https://github.com/majlis-erc/manuForma/assets/73166992/4ba2cf4e-b100-4322-9886-6be8c43a6a66)

**Comment by wsalesky** [comment]
@mMoliere a hard refresh should fix this one as well.

**Comment by mMoliere** [comment]
@wsalesky It is very paradoxical. In some cases it works, sometimes it does not work in the same subform. These are both from content: 
![Screenshot 2023-07-18 at 22 33 27](http
![Screenshot 2023-07-18 at 22 33 36](https://github.com/majlis-erc/manuForma/assets/73166992/19b9311c-3be6-4af9-8c45-67c621b57eaa)
s://github.com/majlis-erc/manuForma/assets/73166992/fbdacd64-7a74-4286-80f8-30ce9d740491)

**Comment by mMoliere** [comment]
@wsalesky Yeah, you are right

**Comment by mMoliere** [comment]
@wsalesky So I reran the forms, but this does not change anything. The schemas still contain all the glosses. Therefore to me it seems that something in the generator is amiss.

**Comment by wsalesky** [comment]
@mMoliere I'm sorry, can you remind me what subform you are seeing this error on?

**Comment by wsalesky** [comment]
@mMoliere 
Okay, we are going to have to do a little troubleshooting together, to make sure I fully understand where the application is going wrong. 

The 'Content description' section is generated using this schema: 
https://github.com/majlis-erc/manuForma/blob/main/forms/schemas/mss-msitem.xml#L467

And I am using this template for testing: 
https://github.com/majlis-erc/manuForma/blob/main/forms/templates/full-mss-template.xml#L95


On this form, I do not see any Language attributes that are not using the controlled vocabulary, but I do see a lot of 'blank attributes' which are not defined (or deleted) in the schema, but still present in the the template. Could they be causing the issue? Screen shot of what I am seeing is below:
 
<img width="1259" alt="Screenshot 2023-07-26 at 11 49 18 AM" src="https://github.com/majlis-erc/manuForma/assets/1168206/484ad4d6-8f9b-4b4b-a06b-6e712e85a638">


All those circled attributes should not be in the template, if we remove them that may solve the issue. Please let me know if I missed something. Or if the issue you are talking about is a different issue. Thanks!

**Comment by mMoliere** [comment]
@wsalesky Thank you for pointing out these inconsistencies!

I have ironed them out, but the bug persists.
![Screenshot 2023-07-27 at 20 27 55](https://github.com/majlis-erc/manuForma/assets/73166992/18d21b8d-7d4f-4454-a439-a15d64b9f007)

**Comment by wsalesky** [comment]
@mMoliere curious. I will take a look and see if I can figure out what is going on. Thanks.

**Comment by wsalesky** [comment]
@mMoliere I'm sorry, I am finding this difficult to diagnose, can you tell me which element and attributes are NOT behaving as you expect them to? And then which subforms they are in?

**Comment by mMoliere** [comment]
@wsalesky Yes, it works like charm!

**Comment by mMoliere** [comment]
@wsalesky Thank you. That works!
